### PR TITLE
gha: Fix nydus namespace clean up

### LINKED ISSUE #9264: gha: fix nydus clean up namespace

### PR DESCRIPTION
**Pull request by GabyCT**
This PR terminates the nydus namespace to avoid the error of that the flag needs an argument.

Fixes #9264

### CODE REVIEW

**Comment by GabyCT** [comment]
@ChengyuZhu6 I noticed that when the CI is executing  https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/gha-run.sh#L436 we can get an error like
```
kubectl get ns nydus-system -o json | jq '.spec.finalizers = []' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f || true
error: flag needs an argument: 'f' in -f
```
which leaves the nydus-system namespace not being properly deleted the correct command is 
```
kubectl get namespace nydus-system -o json | jq 'del(.spec.finalizers)' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f -
```

**Comment by GabyCT** [comment]
@ChengyuZhu6 the nydus-system namespace not  being properly deleted is being seen on the TDX machine

**Comment by GabyCT** [comment]
```
$ kubectl get namespace nydus-system -o json | jq 'del(.spec.finalizers)' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f - || true
{"kind":"Namespace","apiVersion":"v1","metadata":{"name":"nydus-system","uid":"50c6cf37-6c77-489f-a3c7-0bae2f3a01c2","resourceVersion":"4059345","creationTimestamp":"2024-03-13T03:08:25Z","deletionTimestamp":"2024-03-13T03:11:32Z","labels":{"kubernetes.io/metadata.name":"nydus-system"},"managedFields":[{"manager":"kubectl-create","operation":"Update","apiVersion":"v1","time":"2024-03-13T03:08:25Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:kubernetes.io/metadata.name":{}}}}},{"manager":"k3s","operation":"Update","apiVersion":"v1","time":"2024-03-13T03:11:38Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"NamespaceContentRemaining\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionContentFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionDiscoveryFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceDeletionGroupVersionParsingFailure\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"NamespaceFinalizersRemaining\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}},"subresource":"status"}]},"spec":{},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"True","lastTransitionTime":"2024-03-13T03:11:37Z","reason":"DiscoveryFailed","message":"Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: stale GroupVersion discovery: metrics.k8s.io/v1beta1"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2024-03-13T03:11:38Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"False","lastTransitionTime":"2024-03-13T03:11:38Z","reason":"ContentDeleted","message":"All content successfully deleted, may be waiting on finalization"},{"type":"NamespaceContentRemaining","status":"False","lastTransitionTime":"2024-03-13T03:11:38Z","reason":"ContentRemoved","message":"All content successfully removed"},{"type":"NamespaceFinalizersRemaining","status":"False","lastTransitionTime":"2024-03-13T03:11:38Z","reason":"ContentHasNoFinalizers","message":"All content-preserving finalizers finished"}]}}
(failed reverse-i-search)`get naespa': kubectl ^Ct namespace nydus-system -o json | jq 'del(.spec.finalizers)' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f - || true
github-runner@984fee00bd70:/tmp/nydus-snapshotter$ kubectl get namespaces -A
NAME              STATUS   AGE
default           Active   104d
kube-system       Active   104d
kube-public       Active   104d
kube-node-lease   Active   104d
```

**Comment by GabyCT** [comment]
@ChengyuZhu6 now I am seeing errors but in the deployment 
```
nydus snapshotter logs
  error: You must provide one or more resources by argument or filename.
  Example resource specifications include:
     '-f rsrc.yaml'
     '--filename=rsrc.json'
     '<resource> <name>'
     '<resource>'
  Error: Process completed with exit code 1.
```

**Review by ChengyuZhu6 — APPROVED** [review]
LGTM thanks @GabyCT

File: tests/integration/kubernetes/gha-run.sh [hunk 1]
```diff
@@ -433,7 +433,7 @@ function cleanup_nydus_snapshotter() {
 	fi
 	sleep 180s
 	kubectl delete -f "misc/snapshotter/nydus-snapshotter-rbac.yaml"
-	kubectl get ns nydus-system -o json | jq '.spec.finalizers = []' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f || true
+	kubectl get namespace nydus-system -o json | jq 'del(.spec.finalizers)' | kubectl replace --raw "/api/v1/namespaces/nydus-system/finalize" -f - || true
```
Comment (wainersm) [inline tests/integration/kubernetes/gha-run.sh:436]: hi @GabyCT !

The change of `jq '.spec.finalizers = []'` to ` jq 'del(.spec.finalizers)'` is really needed to? I'm just worried that some environments might have different versions of `jq` and this `del` syntax might not be available.

you know, `yq` left some bad marks on my soul...so I am always worried about the backward-compatibility of tools like `jq` too.

Comment (GabyCT) [reply tests/integration/kubernetes/gha-run.sh:436]: @wainersm I tried it with the `jq '.spec.finalizers = []' but it did not work so seems like jq '.spec.finalizers = []' it is needed to properly delete the namespace

Comment (wainersm) [reply tests/integration/kubernetes/gha-run.sh:436]: ah, ok. thanks for the explanation @GabyCT !

**Review by wainersm — APPROVED** [review]
Thanks @GabyCT !
