### PR TITLE
utils: always check some dependencies.

### LINKED ISSUE #6302: Kata Manager should check for dependencies it needs itself even with -f.
Currently, certain dependency checks like curl and tar are skipped when the -f option is passed to kata-manager.sh. This leads to the script failing in ways that may be unintuitive to the user. We should really be performing those checks even when -f is passed.

### PR DESCRIPTION
**Pull request by gabevenberg**
Every dependency in check_deps is used inside the script (apart from git, which may be a historical artifact), and therefore should be checked even when the -f option is passed to the script. Simply changed at what point check_deps is called in order to always run it.

Fixes #6302.

### CODE REVIEW

File: utils/kata-manager.sh [hunk 1]
```diff
@@ -327,7 +327,7 @@ check_deps()
 		debian|ubuntu) sudo apt-get -y install $packages ;;
 		fedora) sudo dnf -y install $packages ;;
 		opensuse*|sles) sudo zypper install -y $packages ;;
-		*) die "Unsupported distro: $ID"
+		*) die "Unsupported distro: $ID, install $packages manually and re-run"
```
Comment (fidencio) [inline utils/kata-manager.sh:330]: Just a tip from the user's perspective, and I know it's been there before your PR. :-)

Drop the "Unsupported distro: " part of the message.  It would make a user run away thinking the whole kata-containers is not supported on that distro, which is not the case.

Comment (gabevenberg) [reply utils/kata-manager.sh]: Done!

**Review by jodh-intel — APPROVED** [review]
Nice! Thanks @gabevenberg!

lgtm

**Comment by jodh-intel** [comment]
Let's fire up the CI (see https://github.com/kata-containers/community/wiki/Controlling-the-CI for a list of commands btw)...

/test

**Comment by jodh-intel** [comment]
> this would also fix https://github.com/kata-containers/kata-containers/issues/6270, btw. @jodh-intel, do I need to make a dummy commit to get gh to close that issue when this is closed, or do we just manually close it?

@gabevenberg - I'll close that manually in a sec. An alternative is to specify multiple "Fixes: #" comment lines so that GH will close all referenced issues when the PR is merge.
