### PR TITLE
agent: add support to provide default agent policy via env

### LINKED ISSUE #10301: agent: Support overriding policy document default path from cmdline/env/config file during initialization for development/testing
**Which feature do you think can be improved?**

kata-agent built with feature '**agent-policy**' initializes the policy engine using the document linked to '/etc/kata-opa/default-policy.rego'.
This document in installed and linked when building the UVM rootfs.

For test setups like that for testing kata-agent APIs using kata-agent-ctl, the kata-agent process built with this feature cannot be started as a local process since this policy document is not available on the host.

Provide a development/testing only enhancement to allow overriding policy document via cmdline/env/config file.

**How can it be improved?**

- support providing a policy document via cmdline/env/config file.
- use the default path in case no overrides provided. 

**Additional Information**
With changes:
[intializes policy using default path]
sudo RUST_BACKTRACE=full KATA_AGENT_LOG_LEVEL=debug KATA_AGENT_SERVER_ADDR=unix://@/tmp/kata-agent.socket /usr/bin/kata-agent

sudo RUST_BACKTRACE=full KATA_AGENT_LOG_LEVEL=debug KATA_AGENT_SERVER_ADDR=unix://@/tmp/kata-agent.socket KATA_AGENT_POLICY_FILE="" /usr/bin/kata-agent

[overrides policy path with that provided in env]
sudo RUST_BACKTRACE=full KATA_AGENT_LOG_LEVEL=debug KATA_AGENT_SERVER_ADDR=unix://@/tmp/kata-agent.socket KATA_AGENT_POLICY_FILE="/tmp/allow-all.rego" /usr/bin/kata-agent

**Before raising this enhancement request**

Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)?

**Kata Containers survey**

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

### PR DESCRIPTION
**Pull request by Sumynwa**
agent built with policy feature initializes the policy engine using a
policy document from a default path, which is installed & linked during
UVM rootfs build. This commit adds support to provide a default agent
policy as environment variable.

This targets development/testing scenarios where kata-agent
is wanted to be started as a local process.

Fixes #10301

### CODE REVIEW

**Comment by sprt** [comment]
@Sumynwa Could you squash your commits into one?

File: src/agent/src/config.rs [hunk 1]
```diff
@@ -38,6 +38,8 @@ const SECURE_STORAGE_INTEGRITY_OPTION: &str = "agent.secure_storage_integrity";
 // to solve the problem of not being able to access the specified image in some cases.
 const HTTPS_PROXY: &str = "agent.https_proxy";
 const NO_PROXY: &str = "agent.no_proxy";
+#[cfg(feature = "agent-policy")]
+const POLICY_FILE_OPTION: &str = "agent.policy_file";
```
Comment (danmihai1) [inline src/agent/src/config.rs:42]: Does this change also allow changing the policy file path using:
1. The kernel command line, and/or
2. A pod annotation?

I vote for blocking these two means of configuration because:
a. They are relatively risky for a CoCo TEE, and 
b. We don't have (yet?) use cases that require them.

File: src/agent/README.md [hunk 2]
```diff
@@ -139,6 +139,7 @@ The kata agent has the ability to configure agent options in guest kernel comman
 | `agent.server_addr` | Server address | Allow the ttRPC server address to be specified | string | `"vsock://-1:1024"` |
 | `agent.trace` | Trace mode | Allow to static tracing | boolean | `false` |
 | `systemd.unified_cgroup_hierarchy` | `Cgroup hierarchy` | Allow to setup v2 cgroups | boolean | `false` |
+| `agent.policy_file` | Policy file path | Allow to specify the policy file path for the agent to initialize policy engine with | string | `"/etc/kata-opa/default-policy.rego"` |
```
Comment (danmihai1) [inline src/agent/README.md:142]: I suggest: "Allow to specify the path to the default agent policy". 

Same for the config.rs comment below.

File: src/agent/src/main.rs [hunk 3]
```diff
@@ -384,10 +384,20 @@ async fn start_sandbox(
...
 
     #[cfg(feature = "agent-policy")]
-    if let Err(e) = initialize_policy().await {
-        error!(logger, "Failed to initialize agent policy: {:?}", e);
-        // Continuing execution without a security policy could be dangerous.
-        std::process::abort();
+    {
+        let mut policy_file = config.policy_file.as_str();
+        if policy_file.is_empty() {
+            warn!(
```
Comment (danmihai1) [inline src/agent/src/main.rs:390]: If I understand correctly, users will see this warning if they don't configure anything, and they are using a Kata CI image. So, we should replace this warning with something like:

info!("Using default policy from {policy_file}");

**Review by danmihai1 — CHANGES_REQUESTED** [review]

File: src/agent/src/main.rs [hunk 4]
```diff
@@ -384,10 +384,20 @@ async fn start_sandbox(
     image::set_proxy_env_vars().await;
 
     #[cfg(feature = "agent-policy")]
-    if let Err(e) = initialize_policy().await {
-        error!(logger, "Failed to initialize agent policy: {:?}", e);
-        // Continuing execution without a security policy could be dangerous.
-        std::process::abort();
+    {
+        let mut policy_file = config.policy_file.as_str();
```
Comment (danmihai1) [inline src/agent/src/main.rs:388]: Can we move this new code into policy.rs?

File: src/agent/README.md (hunk 2 above)
Comment (Sumynwa) [reply src/agent/README.md:142]: Sure. I will change it.

File: src/agent/src/main.rs (hunk 3 above)
Comment (Sumynwa) [reply src/agent/src/main.rs:390]: Yes makes sense. Will correct it.

File: src/agent/src/config.rs (hunk 1 above)
Comment (Sumynwa) [reply src/agent/src/config.rs:42]: Yes @danmihai1 it also allows from kernel cmdline ( and setting cmdline from pod annotations).
Makes sense I will remove this.
As the current use case is only for testing, the environment variable path is sufficient.

File: src/agent/src/policy.rs [hunk 5]
```diff
@@ -85,7 +86,7 @@ impl AgentPolicy {
     }
 
     /// Initialize regorus.
-    pub async fn initialize(&mut self, default_policy_file: &str) -> Result<()> {
+    pub async fn initialize(&mut self, policy_file: &str) -> Result<()> {
```
Comment (danmihai1) [inline src/agent/src/policy.rs:89]: @Sumynwa , would this simplified version work too?

```
    /// Initialize regorus.
    pub async fn initialize(&mut self) -> Result<()> {
        if AGENT_CONFIG.log_level.as_usize() >= slog::Level::Debug.as_usize() {
            self.log_file = Some(
                tokio::fs::OpenOptions::new()
                    .write(true)
                    .truncate(true)
                    .create(true)
                    .open(POLICY_LOG_FILE)
                    .await?,
            );
            debug!(sl!(), "policy: log file: {}", POLICY_LOG_FILE);
        }

        let mut default_policy_file = AGENT_CONFIG.policy_file;
        if default_policy_file.is_empty() {
            default_policy_file = POLICY_DEFAULT_FILE.to_string();
        }
        info!(sl!(), "default policy: {default_policy_file}");

        self.engine.add_policy_from_file(default_policy_file)?;
        self.update_allow_failures_flag().await?;
        Ok(())
    }
```

**Review by danmihai1 — APPROVED** [review]

**Comment by fidencio** [comment]
@Sumynwa, we had some issues with the CI last week, due to that I'd like to ask you to rebase atop of the current main.

File: src/agent/src/policy.rs (hunk 5 above)
Comment (Sumynwa) [reply src/agent/src/policy.rs]: Yes @danmihai1 Made the changes.

**Review by sprt — APPROVED** [review]
LGTM!
