### PR TITLE
runtime-rs: Fix initdata length field missing when create block

### LINKED ISSUE #11556: runtime-rs: initdata length field missing when create initdata block causes read failed within kata-agent
# Get your issue reviewed faster
The init data could not be read properly within kata-agent because the data length field was omitted, a consequence of a mismatch in the data write format.

### PR DESCRIPTION
**Pull request by Apokleos**
The init data could not be read properly within kata-agent because the data length field was omitted, a consequence of a mismatch in the data write format.

Fixes #11556

### CODE REVIEW

**Review by lifupan — APPROVED** [review]

File: src/runtime-rs/crates/resource/src/coco_data/initdata_block.rs [hunk 1]
```diff
@@ -169,22 +169,26 @@ fn create_compressed_block(
...
+    {
+        let mut gz = GzBuilder::new()
+            .filename("initdata.toml") // Embed original filename metadata
+            .comment("Generated by Confidential Containers")
+            .write(&mut compressed_data, compression);
+
+        // Write data in chunks to avoid large memory allocation
+        let mut bytes_written = 0;
+        for chunk in initdata.as_bytes().chunks(buffer_size) {
+            bytes_written += gz.write(chunk)?;
```
Comment (burgerdev) [inline src/runtime-rs/crates/resource/src/coco_data/initdata_block.rs]: Should this be using `write_all`? The generic trait at least does not guarantee all bytes are written: https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.write.

Comment (Apokleos) [reply src/runtime-rs/crates/resource/src/coco_data/initdata_block.rs]: Thx @burgerdev fixed!
