### PR TITLE
gha: delete azure RG only if it exists

### LINKED ISSUE #8989: CI: azure aks deploy sometimes fail to find the resources group
Recently I've noticed some CI jobs that relies on AKS provisioning failing because the Azure resource group (which is created on-demand before creating the cluster) is not found:

For example, https://github.com/kata-containers/kata-containers/actions/runs/7724334694/job/21074189970?pr=8839 and https://github.com/kata-containers/kata-containers/actions/runs/7722583170/job/21076489139?pr=8974, you will see an error similar to:

```
ERROR: (ResourceGroupNotFound) Resource group 'kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found.
{
  "id": "/subscriptions/***/resourceGroups/kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s",
  "location": "eastus2",
  "managedBy": null,
  "name": "kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
WARNING: The behavior of this command has been altered by the following extension: aks-preview
WARNING: SSH key files '/home/runner/.ssh/id_rsa' and '/home/runner/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud Shell without an attached file share, back up your keys to a safe location
ERROR: (ResourceGroupNotFound) Create or update resource group node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s failed. autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found."
Code: ResourceGroupNotFound
Message: Create or update resource group node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s failed. autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found."
Exception Details:	(ResourceGroupNotFound) Resource group 'node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found.
	Code: ResourceGroupNotFound
	Message: Resource group 'node-kataCI-k8s-8839-27c908f10757-qemu-ubuntu-amd64-s' could not be found.
Error: Process completed with exit code 1.
```

On https://github.com/kata-containers/kata-containers/blob/main/tests/gha-run-k8s-common.sh#L68 it is **requested** the creation the aforementioned resource group but it doesn't wait the resource to effectively exist. That might be the problem.

### PR DESCRIPTION
**Pull request by wainersm**
delete_cluster() has tried to delete the az resources group regardless if it exists. In some cases the result of that operation is ignored, i.e., fail to resource group not found, but the log messages get a little dirty. Let's delete the RG only if it exists then.

Fixes #8989
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

---

Split of https://github.com/kata-containers/kata-containers/pull/8990

### CODE REVIEW

File: tests/gha-run-k8s-common.sh [hunk 1]
```diff
@@ -104,10 +104,14 @@ function get_cluster_credentials() {
...
 function delete_cluster() {
     test_type="${1:-k8s}"
-
-    az group delete \
-        -g "$(_print_rg_name ${test_type})" \
-        --yes
+    local rg
+    rg="$(_print_rg_name ${test_type})"
+
+    if [ "$(az group exists -n "${rg}")" == "true" ]; then
```
Comment (sprt) [inline tests/gha-run-k8s-common.sh:110]:
```suggestion
    if [ "$(az group exists -g "${rg}")" == "true" ]; then
```
If we want to be consistent with other commands.

File: tests/gha-run-k8s-common.sh [hunk 2]
```diff
@@ -104,10 +104,14 @@ function get_cluster_credentials() {
...
+        az group delete \
+            -g "${rg}" \
+            --yes
```
Comment (sprt) [inline tests/gha-run-k8s-common.sh:113]:
```suggestion
        az group delete -g "${rg}" --yes
```
Tiny bit more readable.

**Review by sprt — APPROVED** [review]
LGTM, thank you Wainer! Left a couple nits but happy to merge as is. 🙂

**Comment by wainersm** [comment]
Just updated to address @sprt 's suggestions.

**Review by danmihai1 — APPROVED** [review]

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!
