### PR TITLE
kata-types: fix bug in kata-types several test cases

### LINKED ISSUE #9783: kata-types: do cargo test failed with some test cases
# Get your issue reviewed faster

kata-types: do cargo test failed with some test cases

### PR DESCRIPTION
**Pull request by Apokleos**
Fixes #9783

### CODE REVIEW

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Review by lifupan — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

File: src/libs/kata-types/src/capabilities.rs [hunk 1]
```diff
@@ -132,6 +132,6 @@ mod tests {
         // test append capabilities
         cap.add(CapabilityBits::GuestMemoryProbe);
         assert!(cap.is_mem_hotplug_probe_supported());
-        assert!(cap.is_fs_sharing_supported());
+        assert!(!cap.is_fs_sharing_supported());
```
Comment (amshinde) [inline src/libs/kata-types/src/capabilities.rs:135]: @Apokleos Why this change here?  On line 125 `FsSharingSupport` is being set and dont see it being unset anywhere. 
Why are you checking for false value here?

File: src/libs/kata-types/tests/texture/configuration-anno-0.toml [hunk 2]
```diff
@@ -84,6 +84,7 @@ sandbox_bind_mounts=["/proc/self"]
 vfio_mode="vfio"
 experimental=["a", "b"]
 enable_pprof = true
+name="virt-container"
```
Comment (amshinde) [inline src/libs/kata-types/tests/texture/configuration-anno-0.toml:87]: Why is this change needed? Can you add some explanation in the commit message?

File: src/libs/kata-types/src/capabilities.rs (hunk 1 above)
Comment (Apokleos) [reply src/libs/kata-types/src/capabilities.rs:135]: Thx @amshinde good catch !
As L130 cap does set causing previous Caps replaced by `CapabilityBits::HybridVsockSupport` and then there's no other Caps existing. with such reason, the  `assert!(cap.is_fs_sharing_supported());` failed. 
I rechecked the test case, the root cause is L130. It should be changed to ` cap.add(CapabilityBits::HybridVsockSupport);` and the L135 keep it was.

File: src/libs/kata-types/tests/texture/configuration-anno-0.toml (hunk 2 above)
Comment (Apokleos) [reply src/libs/kata-types/tests/texture/configuration-anno-0.toml:87]: Ok, comments to be added. The explanation is , it will return error if no such name setting when do 
``` code
update_config_by_annotation {
    ...
if config.runtime.name.is_empty() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "Runtime name is missing in the configuration",
            ));
        }
...
}
```

But I am curious about our CIs no-run with UT ?

Comment (amshinde) [reply src/libs/kata-types/tests/texture/configuration-anno-0.toml:87]: Ok, thanks for the explanation and updating the commit message. Yes, I am a bit surprised why the CI did not catch this. Can you look into it?

**Review by amshinde — APPROVED** [review]

File: src/libs/kata-types/tests/texture/configuration-anno-0.toml (hunk 2 above)
Comment (Apokleos) [reply src/libs/kata-types/tests/texture/configuration-anno-0.toml:87]: Yes, I will spend some time to check why CI doesn't run into these parts. And I will sync with you.
