### PR TITLE
osbuilder: Enable dbus in the dracut case

### LINKED ISSUE #6657: Kata agent fails to connect to systemd
When the guest image has systemd as init (as created with dracut), the agent terminates and the following error is returned :

```
Caused by:
    0: Establishing a D-Bus connection
    1: I/O error: No such file or directory (os error 2)
    2: No such file or directory (os error 2): unknown 
```

This is the yet another consequence of #5154 : D-Bus should be enabled in the guest if the agent needs to talk to systemd.

### PR DESCRIPTION
**Pull request by gkurz**
The agent now offloads cgroup configuration to systemd when possible. This requires to enable D-Bus in order to communicate with systemd.

Fixes #6657

### CODE REVIEW

**Review by jepio — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @gkurz!

**Comment by gkurz** [comment]
> lgtm, thanks @gkurz!

Thanks @jepio and @fidencio ! :smile:

File: tools/osbuilder/rootfs-builder/rootfs.sh [hunk 1]
```diff
@@ -475,6 +475,8 @@ prepare_overlay()
 	# Kata systemd unit file
 	mkdir -p ./etc/systemd/system/basic.target.wants/
 	ln -sf /usr/lib/systemd/system/kata-containers.target ./etc/systemd/system/basic.target.wants/kata-containers.target
+	mkdir -p ./etc/systemd/system/kata-containers.target.wants/
+	ln -sf /usr/lib/systemd/system/dbus.socket  ./etc/systemd/system/kata-containers.target.wants/dbus.socket
```
Comment (c3d) [inline tools/osbuilder/rootfs-builder/rootfs.sh:479]: I know this was done that way before, but why is there an absolute path for /usr but a relative one for ./etc? I assume that it's because it's a symbolic link and you want the path as it exists on the target?

**Review by c3d — APPROVED** [review]
FWIW, looks good to me, thanks @gkurz

File: tools/osbuilder/rootfs-builder/rootfs.sh (hunk 1 above)
Comment (gkurz) [reply tools/osbuilder/rootfs-builder/rootfs.sh:479]: > I know this was done that way before, but why is there an absolute path for /usr but a relative one for ./etc? I assume that it's because it's a symbolic link and you want the path as it exists on the target?

The first argument to `ln -s` is basically just a string that will be parsed at runtime when the symbolic link is traversed. The second argument is the path of the actual symbolic link we're creating. So yes, your assumption is correct.

Comment (Vlad1mir-D) [reply tools/osbuilder/rootfs-builder/rootfs.sh:479]: @gkurz Why not to insert the same logic here: https://github.com/gkurz/kata-containers/blob/eb1762e813c52d5b593bacb04932d6fbf0ca3a19/tools/osbuilder/rootfs-builder/rootfs.sh#L630?

Comment (gkurz) [reply tools/osbuilder/rootfs-builder/rootfs.sh:479]: > @gkurz Why not to insert the same logic here: https://github.com/gkurz/kata-containers/blob/eb1762e813c52d5b593bacb04932d6fbf0ca3a19/tools/osbuilder/rootfs-builder/rootfs.sh#L630?

Hi @Vlad1mir-D ! Thanks for reporting this. I simply missed it :disappointed: . Let's address this with #6677 .
