### PR TITLE
runtime: Fix trace span ordering and static checks

### LINKED ISSUE #1550: Tracing span ordering is incorrect again
Issue https://github.com/kata-containers/kata-containers/issues/1355 and PR https://github.com/kata-containers/kata-containers/pull/1389 fixed tracing span ordering by passing a local context and not using a shim or service struct in functions outside of containerd-shim-v2 (where a root span is created). 

https://github.com/kata-containers/kata-containers/pull/1539 fixes failed static checks (ineffective assignments), some of which involve `trace()` functions. The `trace()` functions create a span and associate a span with a context, which are both returned. If the context is not returned and the `ctx` from the original calling function is passed to subsequent ones that eventually use `trace()`, the subsequent spans will have incorrect ordering because `ctx` was not associated with the appropriate parent span. 

In some cases in #1539, the changes prevent `ctx` from being associated with a span, which results in incorrect span ordering since `ctx` is passed to subsequent calls. However, if returning `ctx` in `trace()` caused static checks to fail after #1539's fixes, we need to find a compromise where 1) static checks pass and 2) trace spans are ordered correctly.

cc @bergwolf @liubin @egernst

### PR DESCRIPTION
**Pull request by cmaf**
Return ctx in trace() functions to correct span ordering.

Fixes #1550

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
Previous ordering: 
tracing_ordering1

Fixed ordering:
tracing_ordering2

**Review by jcvenegas — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by cmaf** [comment]
Please do not merge until issue is discussed

File: src/runtime/containerd-shim-v2/service.go [hunk 1]
```diff
@@ -301,7 +301,7 @@ func trace(ctx context.Context, name string) (otelTrace.Span, context.Context) {
 }
 
 func (s *service) Cleanup(ctx context.Context) (_ *taskAPI.DeleteResponse, err error) {
-	span, _ := trace(s.rootCtx, "Cleanup")
+	span, spanCtx := trace(s.rootCtx, "Cleanup")
```
Comment (bergwolf) [inline src/runtime/containerd-shim-v2/service.go:304]: What is the rule of spanning trace context here? I see that some places are using previously saved context, others are using the passed down `ctx`. We need to unify them.

**Review by bergwolf — APPROVED** [review]

File: src/runtime/containerd-shim-v2/service.go (hunk 1 above)
Comment (egernst) [reply src/runtime/containerd-shim-v2/service.go:304]: @bergwolf - when we receive requests from containerd (or crio if they pass contexts, I'm not sure), they are tied to the life of the particular task service function or to the shim itself.

Based on that, we have a context that has notion of being tied to lifecycle of the sandbox, as well as contexts which are tied to a particular request.

I think it makes sense to use the context from the specific request whenever possible, so we can have spans that run from containerd down to the agent in the guest. However, we'll need to make sure to use the long running ctx for functions which are dependent on it (IIRC -we pass a context to ttRPC?)

Comment (cmaf) [reply src/runtime/containerd-shim-v2/service.go:304]: @bergwolf in containerd-shim-v2 I added rootCtx so that all of the trace spans are organized under a single root span, which is associated with a root context. This was done based on feedback in previous issues and PRs that people wanted spans organized this way. (We don't actually need to do this; we  could use the contexts passed into calls in service.go. It will just change the organization of them so that they are not grouped under a single root span.) 

Aside from create.go and service.go, where tracing is started and higher level spans are created, for tracing we typically want to use a context passed to the function to get properly ordered spans. 

I agree with @egernst here. I avoided changing the use of a service or shim struct if it was used for anything other than tracing, so if there are instances of this it is a bug.
