### PR TITLE
runtime-rs: handle container missing during kill_process gracefully

### LINKED ISSUE #12120: runtime-rs: Handle container not found errors gracefully during kill_process
# Description of Problem
The Rust Kata runtime fails to handle "container not found" errors gracefully during `kill_process()`, causing pods to get stuck in `Terminating` state indefinitely. This creates a metadata desync between the Kata agent, containerd, and kubelet.

## Root Cause

The Rust runtime's `kill_process()` method checks if a container exists in its internal HashMap **before** attempting to kill it. If the container is missing (e.g., QEMU process died, VM crashed, race condition), it returns an error:

**Rust kill_process()**
```rust
let c = containers
    .get(container_id)
    .ok_or_else(|| Error::ContainerNotFound(container_id.clone()))?
```

This error propagates to containerd/kubelet, which interprets it as "container still running, kill failed" and retries indefinitely.

## Golang Runtime
The Golang runtime handles this gracefully by:
1. Not checking HashMap before kill and attempting the kill operation directly
2. Swallowing ESRCH error by treating "No such process" as success 

**Golang `kill()`
```go
// kill(2) method can return ESRCH in certain cases, which is not handled by
// containerd cri server in container_stop.go. CRIO server also doesn't handle
// ESRCH. So kata runtime will swallow it here.
if err = c.sandbox.agent.signalProcess(ctx, c, processID, signal, all); err != nil &&
    strings.Contains(err.Error(), "ESRCH: No such process") {
    return nil  // ← Returns success!
}
```

**Code References:**
- Golang `kill()`: https://github.com/kata-containers/kata-containers/blob/89cd5613401a9585d023fce2534c13d9f79d9f2d/src/runtime/virtcontainers/container.go#L1369-L1394
- Rust `kill_process()`: https://github.com/kata-containers/kata-containers/blob/89cd5613401a9585d023fce2534c13d9f79d9f2d/src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs#L219-L237

## Impact

When containers have preStop hooks, kubelet attempts to exec them in non-existent containers, causing infinite retry loops. Pods remain stuck in `Terminating` state until manual cleanup (force delete).

## Scenarios That Trigger This Bug

1. **QEMU process dies** (OOM, crash, manual kill)
2. **VM reboots** (kernel panic, agent crash)
3. **Container crashes inside VM** (agent removes it, but shim HashMap still has it)
4. **Race condition** between kill and delete operations
5. **Containerd restart** (reconciliation attempts)

# Reproduction Steps

## Prerequisites
- Kubernetes cluster with Rust Kata runtime
- Node with kata-qemu runtime class

## Steps

1. **Deploy test pod with preStop hook:**

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test-zombie-pod
  namespace: kata-test
spec:
  runtimeClassName: kata
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: "${NODE_NAME}"
  containers:
  - name: main
    image: busybox:1.35.0
    command: ["/bin/sh", "-c", "echo 'Main container started'; sleep infinity"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: sidecar-with-prestop
    image: busybox:1.35.0
    command: ["/bin/sh", "-c", "echo 'Sidecar started'; sleep infinity"]
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - echo "Running preStop hook"; sleep 5; echo "preStop complete"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
EOF
```

2. **Kill the QEMU process (simulates VM crash/OOM):**

```bash
# SSH to the node
node-shell "${NODE_NAME}"

# Find and kill QEMU process
SANDBOX_ID=$(crictl pods --name test-zombie-pod --namespace kata-test -q)
QEMU_PID=$(ps aux | grep qemu | grep ${SANDBOX_ID} | grep -v grep | awk '{print $2}')
kill -9 "${QEMU_PID}"
```

3. **Attempt to delete the pod:**

```bash
kubectl delete pod test-zombie-pod -n kata-test
```

4. **Observe zombie pod stuck in Terminating:**

```bash
kubectl get pod test-zombie-pod -n kata-test
# Output: NAME              READY   STATUS        RESTARTS   AGE
#         test-zombie-pod   0/2     Terminating   0          5m
```

## Expected Error Logs

```
Error syncing pod, skipping" err="detected running containers after a successful KillPod, CRI violation: [containerd://4c8162411263c9c0a5434c2b97450243994105eefc4b9ef450b327f444eeb13b]

E1118 20:07:06.973885   23567 kuberuntime_container.go:692] "PreStop hook failed" err="rpc error: code = NotFound desc = failed to exec in container: failed to load task: no running task found: task 4c8162411263c9c0a5434c2b97450243994105eefc4b9ef450b327f444eeb13b not found: not found" pod="kata-test/test-zombie-pod-2" podUID="cf5b7ae0-56d2-45b4-80ab-35e2d7a4908b" containerName="sidecar-with-prestop"
```

This same test on golang runtime allows pods to be deleted without being stuck in terminating 

# Expected Behavior

According to [CRI specs](https://github.com/kubernetes/cri-api/blob/6e530f34d00cb2f7069e63117eb25d9dbc5283ca/pkg/apis/runtime/v1/api.proto#L56-L61), `StopPodSandbox()` must be **idempotent** and should not return an error if the sandbox is already stopped.

Killing a container should:
1. Not depend on HashMap state - Attempt the kill operation regardless
2. Treat "not found" as success - Container already dead = goal achieved
3. Match Golang runtime behavior - Swallow ESRCH errors

# Actual Behavior

The `kill_process()` call fails if the container has been removed from the HashMap. The container never gets re-added, creating an **unrecoverable state**.

## The Infinite Loop

```
1. kill_process() fails → Returns error to containerd
2. Containerd keeps container as "RUNNING" in metadata
3. Kubelet sees "RUNNING" → Tries to run preStop hooks
4. preStop hooks fail (can't exec in dead container)
5. Kubelet retries forever
6. Pod stuck in "Terminating" state indefinitely
```

**Manual intervention required:** Force delete with `kubectl delete pod --force --grace-period=0`

# Proposed Solution

Make Rust runtime behavior match Golang runtime:

## 1. Handle Container Not in HashMap

```rust
let c = match containers.get(container_id) {
    Some(c) => c,
    None => {
        // Container already removed - this is OK for SIGKILL/SIGTERM
        if req.signal == 9 || req.signal == 15 {
            warn!(sl!(), "Container already removed, treating as success");
            return Ok(());  // ← Return success!
        }
        return Err(Error::ContainerNotFound(container_id.clone()).into());
    }
};
```

## 2. Handle ESRCH from Agent

```rust
c.kill_process(&req.process, req.signal, req.all)
    .await
    .or_else(|err| {
        let err_str = format!("{:?}", err);
        if err_str.contains("failed to find container")
            || err_str.contains("ESRCH")
            || err_str.contains("No such process") {
            warn!(sl!(), "Signal encounters ESRCH, process already finished");
            Ok(())  // ← Swallow error, return success!
        } else {
            Err(err)
        }
    })
```

# Environment

- **Affected:** GKE, AKS (Rust Kata runtime)
- **Kata Version:** 3.23
- **Kubernetes Version:** 1.32.7

# Additional Context

This bug affects **all unexpected container deaths**, not just OOM scenarios:
- VM crashes
- QEMU process killed
- Agent failures
- Race conditions during pod deletion

## Why This Matters for CRI Compliance

From the [Golang runtime comments](https://github.com/kata-containers/kata-containers/blob/89cd5613401a9585d023fce2534c13d9f79d9f2d/src/runtime/pkg/containerd-shim-v2/service.go#L832-L846):

> According to CRI specs, kubelet will call StopPodSandbox() at least once before calling RemovePodSandbox, and this call is idempotent, and must not return an error if all relevant resources have already been reclaimed.

The Rust runtime violates this CRI requirement by returning errors when resources are already reclaimed.

### PR DESCRIPTION
**Pull request by M-Phansa**
Fixes #12120

**Problem**
When the QEMU VM is killed externally (e.g., OOM killer, `kill -9`), pods using the Rust runtime (`runtime-rs`) get stuck in `Terminating` state indefinitely. This violates CRI specs which require `StopPodSandbox()` to be idempotent.

**Root Cause**
When the VM dies, the ttrpc connection between the shim and kata-agent becomes invalid. When kubelet calls `StopContainer` (which sends SIGKILL/SIGTERM), the Rust runtime attempts to signal the container via ttrpc and receives connection errors like:
- `"ttrpc: local stream closed"`
- `"stream closed"`
- `"connection refused"`

The Rust runtime was propagating these errors back to containerd, causing an unrecoverable state where containerd keeps retrying, kubelet keeps attempting preStop hooks, and pods remain stuck.

The Go runtime avoids this by checking if the process status is `STOPPED` before attempting to signal:
https://github.com/kata-containers/kata-containers/blob/89cd5613401a9585d023fce2534c13d9f79d9f2d/src/runtime/pkg/containerd-shim-v2/service.go#L839-L846

## Changes

In `kill_process()`: For SIGKILL/SIGTERM signals, treat ttrpc connection errors as success since a dead VM means the container is effectively terminated.

## Note on ESRCH

The Go runtime also has code to swallow `ESRCH` ("No such process") errors:
https://github.com/kata-containers/kata-containers/blob/89cd5613401a9585d023fce2534c13d9f79d9f2d/src/runtime/virtcontainers/container.go#L1382-L1392

However, this is **not needed in the shim** because the kata-agent already handles ESRCH internally and never propagates it:
https://github.com/kata-containers/kata-containers/blob/5a5c43429e6253126b84a7304486658fd310ced8/src/agent/src/rpc.rs#L472-L484

## CRI Compliance

Per [CRI specs](https://github.com/kubernetes/cri-api/blob/6e530f34d00cb2f7069e63117eb25d9dbc5283ca/pkg/apis/runtime/v1/api.proto#L56-L61), stop operations must be idempotent and must not return errors if resources are already reclaimed.

## Testing

Tested by killing the QEMU VM process while a pod is running:

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test-zombie-pod
  namespace: kata-test
spec:
  runtimeClassName: kata
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: "${NODE_NAME}"
  containers:
  - name: main
    image: busybox:1.35.0
    command: ["/bin/sh", "-c", "echo 'Main container started'; sleep infinity"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  - name: sidecar-with-prestop
    image: busybox:1.35.0
    command: ["/bin/sh", "-c", "echo 'Sidecar started'; sleep infinity"]
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - echo "Running preStop hook"; sleep 5; echo "preStop complete"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
EOF
```

```bash
SANDBOX_ID=$(crictl pods --name test-zombie-pod --namespace kata-system -q)
QEMU_PID=$(ps aux | grep qemu | grep ${SANDBOX_ID} | grep -v grep | awk '{print $2}')
kill -9 "${QEMU_PID}"
```

Logs from `journalctl -t kata` showing the fix in action:
```
Nov 29 06:54:18 kata[3868112]: QemuInner::stop_vm(): kill()'ing qemu
Nov 29 06:54:18 kata[3868112]: Signal encounters expected error, VM already terminated
```
**Sandbox ID issues after kill -9**
The bug occurs because with the Sandbox API, the sandbox VM is created and started, but no corresponding “sandbox container” entry (with ID = sandbox_id) is added to the container map, while containerd still calls State(sandbox_id) as if it were a normal container. Runtime‑rs therefore fails the lookup in VirtContainerManager.containers and returns a “container not found” error for the sandbox ID.

The fix is to special‑case this in state_process: if container_id == self.sid and it’s not in the containers map, we return a synthetic ProcessStateInfo for the sandbox container, using the shim PID and marking its status as Running. This preserves existing behavior for the Task API (where the sandbox container is in the map) while making the Sandbox API path correctly report state for the sandbox ID.

This is necessary to allow pods to exit terminating state successfully - after adding this the pod was able to be deleted.

**Result:** 
Pod restarts successfully instead of getting stuck in `Terminating` state. This matches the Go runtime's behavior.

Pods can be deleted successfully after restarting this way - all containers exit successfully

### CODE REVIEW

**Comment by Apokleos** [comment]
Thx @M-Phansa for this work.
The one of required CIs reports that you first correct the commit message:
```
  af0e49523bac608e6f2cca248a029450a62b2140    Failed to find subsystem in subject
  9a44beb44d009cd65ad87e2f649b46a3b01cb560    Failed to find subsystem in subject
  7f68c2e2094a3dfd35332b8fd005494686659011    Failed to find subsystem in subject
  dacf5b50b3de79083d4cfe3ae2f36abb411aa2b6    Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
```
And, you'd better follow this patch-format https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs [hunk 1]
```diff
@@ -430,6 +430,32 @@ impl Container {
         all: bool,
     ) -> Result<()> {
         let mut inner = self.inner.write().await;
+
+        // Match Go runtime behavior: check if process is already stopped before signaling.
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs]: It is nice to let reviewers know your original idea, however it is not necessary to mention matching go runtime here. You can only keep the key description about this code, and move the trivial part to the PR body (btw, you've written it well).

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs [hunk 2]
```diff
@@ -430,6 +430,32 @@ impl Container {
...
+        // For SIGKILL/SIGTERM, if the process is already stopped, return success immediately.
+        // This is critical for proper cleanup when VM dies - the wait thread sets status to
+        // Stopped even on error, so subsequent Kill() calls will see it as already stopped.
+        // See: src/runtime/pkg/containerd-shim-v2/service.go lines 839-846
+        let is_termination_signal = signal == 9 || signal == 15; // SIGKILL or SIGTERM
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs]: Replace the hard-coded values, `9` and `15`, with `libc::SIGKILL` and `libc::SIGTERM`, respectively.

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 3]
```diff
@@ -212,28 +212,87 @@ impl ContainerManager for VirtContainerManager {
...
-        .context("exec")?;
-        Ok(())
+        .or_else(|err| {
+            let err_str = format!("{:?}", err);
+            if err_str.contains("failed to find container") {
+                warn!(sl!(), "Container not found during exec, already terminated");
+                Err(Error::ContainerNotFound(container_id.clone()).into())
+            } else {
+                Err(err).context("exec")
+            }
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Well, matching error string literally is not a good practice in Rust. Perhaps, you have to define an error enum for `Container:: exec_process()` , and use `downcast_ref()` to downcast the `anyhow:Error` to the error you defined.

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 4]
```diff
@@ -212,28 +212,87 @@ impl ContainerManager for VirtContainerManager {
...
+
+        // According to CRI specs, kubelet will call StopPodSandbox()
+        // at least once before calling RemovePodSandbox and this call
+        // is idempotent. It must not return an error if all relevant
+        // resources have already been reclaimed
+        let c = match containers.get(container_id) {
+            Some(c) => c,
+            None => {
+                // Container already removed - this is OK for SIGKILL/SIGTERM
+                if req.signal == 9 || req.signal == 15 {
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Ditto.

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 5]
```diff
@@ -212,28 +212,87 @@ impl ContainerManager for VirtContainerManager {
...
         c.kill_process(&req.process, req.signal, req.all)
             .await
-            .map_err(|err| {
-                warn!(
-                    sl!(),
-                    "failed to signal process {:?} {:?}", &req.process, err
-                );
-                err
+            .or_else(|err| {
+                let err_str = format!("{:?}", err);
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Ditto.

**Review by justxuewei — COMMENTED** [review]
Thanks for your great work, some comments here:

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs (hunk 1 above)
Comment (M-Phansa) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs]: Updated comments

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs (hunk 2 above)
Comment (M-Phansa) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs]: Fixed all usages to use the libc signals

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs (hunk 3 above)
Comment (M-Phansa) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Added some new enums / remove the string contains checking - could use some looking over

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs [hunk 6]
```diff
@@ -287,11 +288,39 @@ impl ContainerInner {
...
+                | ttrpc::error::Error::RemoteClosed
+                | ttrpc::error::Error::Eof => {
+                    return Error::AgentConnectionClosed.into();
+                }
+                // Handle errors returned by the agent (RPC status errors)
+                ttrpc::error::Error::RpcStatus(status) => {
+                    if status.code() == ttrpc::Code::NOT_FOUND {
+                        return Error::ProcessAlreadyTerminated.into();
+                    }
+                    if status.message().contains("cannot find init process") {
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs]: This matching highly relies on the implementation of `find_container_process()`, which is brittle. Please define another error enum for the method.

Comment (justxuewei) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs]: Maybe add a new ttrpc code for this case?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 7]
```diff
@@ -212,28 +212,80 @@ impl ContainerManager for VirtContainerManager {
             oci_process,
         )
         .await
-        .context("exec")?;
-        Ok(())
+        .or_else(|err| {
+            if let Some(Error::ContainerNotFound(_)) = err.downcast_ref::<Error>() {
+                warn!(sl!(), "Container not found during exec, already terminated");
```
Comment (justxuewei) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: The error is returned to the upper layer, no need to log a warning, IMHO.

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 8]
```diff
@@ -303,11 +355,31 @@ impl ContainerManager for VirtContainerManager {
...
-            .get(container_id)
-            .ok_or_else(|| Error::ContainerNotFound(container_id.clone()))?;
-        let state = c.state_process(process).await.context("state process")?;
-        Ok(state)
+
+        // When using Sandbox API, the sandbox container (container_id == sandbox_id)
+        // is not stored in the containers map. Return a synthetic state for it.
+        if let Some(c) = containers.get(container_id) {
+            let state = c.state_process(process).await.context("state process")?;
+            Ok(state)
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: The unwrap operation is unnecessary.

```
c.state_process(process).await.context("state process")
```

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 9]
```diff
@@ -303,11 +355,31 @@ impl ContainerManager for VirtContainerManager {
...
+        } else if container_id == &self.sid {
+            // Sandbox container state - return synthetic state
+            use common::types::ProcessStatus;
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Please move it to the "use" block section at the beginning of the file.

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs [hunk 10]
```diff
@@ -361,38 +361,38 @@ impl Process {
             };
 
             info!(logger, "begin wait process");
-            let resp = match agent.wait_process(req).await {
-                Ok(ret) => ret,
+            // If wait_process fails (e.g., VM died), we still set status to Stopped
+            // This ensures that subsequent Kill() calls see the process as already stopped and return success.
+            let exit_code = match agent.wait_process(req).await {
+                Ok(ret) => {
+                    info!(logger, "end wait process exit code {}", ret.status);
```
Comment (justxuewei) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs]: Downgrade the level to debug?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs [hunk 11]
```diff
@@ -287,11 +288,39 @@ impl ContainerInner {
...
             .signal_process(agent::SignalProcessRequest { process_id, signal })
-            .await?;
+            .await
+            .map_err(|e| Self::convert_agent_error(e))?;
 
         Ok(())
     }
 
+    /// Convert agent/ttrpc errors into typed Error enum variants.
+    fn convert_agent_error(err: anyhow::Error) -> anyhow::Error {
```
Comment (Apokleos) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs]: If the method `convert_agent_error` is moved out of this block and made as a public mehod, does it make sense ?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 12]
```diff
@@ -212,28 +212,80 @@ impl ContainerManager for VirtContainerManager {
...
-        .context("exec")?;
-        Ok(())
+        .or_else(|err| {
+            if let Some(Error::ContainerNotFound(_)) = err.downcast_ref::<Error>() {
+                warn!(sl!(), "Container not found during exec, already terminated");
+                Err(Error::ContainerNotFound(container_id.clone()).into())
+            } else {
+                Err(err).context("exec")
+            }
+        })
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: `RuntimeHandlerManager::handler_task_request()` can print the stack if encountering error.

```rust
cm.exec_process(req).await.context("exec")?;
```

I can't see necessity to downcast the error and log a warning.

Comment (xavier-niu) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: An off-topic comment: I think the context, `"exec"`, can't be same as the caller. Could we modify it to `"container exec"`, or something else?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 13]
```diff
@@ -212,28 +212,80 @@ impl ContainerManager for VirtContainerManager {
...
+        // is idempotent. It must not return an error if all relevant
+        // resources have already been reclaimed
+        let c = match containers.get(container_id) {
+            Some(c) => c,
+            None => {
+                // Container already removed - this is OK for SIGKILL/SIGTERM
+                if req.signal == libc::SIGKILL as u32 || req.signal == libc::SIGTERM as u32 {
+                    warn!(
+                        sl!(),
+                        "Container already removed, treating as success";
```
Comment (xavier-niu) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: Kill request ignored due to container not existing

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs (hunk 6 above)
Comment (M-Phansa) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs]: Updating some agent code to propogate the error as one approach to address this

File: src/agent/src/rpc.rs [hunk 14]
```diff
@@ -72,7 +72,7 @@ use crate::network::setup_guest_dns;
 use crate::passfd_io;
 use crate::pci;
 use crate::random;
-use crate::sandbox::Sandbox;
+use crate::sandbox::{Sandbox, SandboxError};
```
Comment (xavier-niu) [inline src/agent/src/rpc.rs:75]: Please split the changes regarding kata-agent into another commit.

Comment (M-Phansa) [reply src/agent/src/rpc.rs:75]: Should I make a separate pr for this? or keep it as part of this pr but a different commit

Comment (xavier-niu) [reply src/agent/src/rpc.rs:75]: Keep it as part of this PR please.

**Comment by xavier-niu** [comment]
Please fix the CI failures.

**Comment by M-Phansa** [comment]
Okay I think I fixed all the build failures - 
The other checks are failing with issues seem unrelated to my changes (download errors/flakiness) - can they be ran again?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs [hunk 15]
```diff
@@ -212,28 +212,74 @@ impl ContainerManager for VirtContainerManager {
...
+        // container is effectively terminated.
         c.kill_process(&req.process, req.signal, req.all)
             .await
-            .map_err(|err| {
-                warn!(
-                    sl!(),
-                    "failed to signal process {:?} {:?}", &req.process, err
+            .or_else(|err| {
+                let is_termination_signal =
+                    req.signal == libc::SIGKILL as u32 || req.signal == libc::SIGTERM as u32;
```
Comment (Apokleos) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs]: As the code changes, I notice that the judgement of `req.signal == libc::SIGKILL as u32 || req.signal == libc::SIGTERM as u32` is used so many times. Shall we make it a public mehod to call ?

File: src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs [hunk 16]
```diff
@@ -361,38 +361,38 @@ impl Process {
...
+                    ret.status
+                }
                 Err(e) => {
+                    // Don't return early - continue to set status to Stopped
                     error!(logger, "failed to wait process {:?}", e);
-                    return;
+                    255
```
Comment (Apokleos) [inline src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs]: what's the numeric 255 for ? and why use it ? If indeed needed, shall we use libc::SIGMAX instead of it ?

Comment (M-Phansa) [reply src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs]: Responding to all comment here - 

Made some of the functions public ->
For the 255 code matching golang behavior / its a containerd exit code
https://github.com/kata-containers/kata-containers/blob/3db7b88efff4e386a919c2df38a14cf401049509/src/runtime/pkg/containerd-shim-v2/wait.go#L59

**Review by Apokleos — APPROVED** [review]
Thx @M-Phansa for your excellent work and your patient. LGTM
