### PR TITLE
runtime(-rs): rootfs: Use dm-mod.create kernel parameters for dm-verity protected root filesystems

### LINKED ISSUE #10959: kata-containers-initrd-confidential.img: fails to launch debug console
# Description of problem

With `oras pull ghcr.io/kata-containers/cached-artefacts/rootfs-initrd-confidential:latest-main-x86_64` (as of today) and unpacked and configured, I ran a `kata-qemu-tdx` pod to connect to a debug console.

# Expected result

```
sudo /opt/kata/bin/kata-runtime exec <sandbox id>
root@localhost:/#
```

# Actual result

```
sudo /opt/kata/bin/kata-runtime exec <sandbox id>
: applet not found
```

# Further information

I had to pull "latest" since v3.14.0 coco initrd fails to run. The debug console works with the rootfs image using the latest build.

### PR DESCRIPTION
**Pull request by manuelh-dev**
This PR changes the flow when building with `MEASURED_ROOTFS` enabled. When a dm-verity protected root filesystem image is built, the corresponding kernel no longer receives the built-in initramfs for mounting the dm-verity device. Instead, we use the `CONFIG_DM_INIT` and proper kernel command line `dm-mod.create` parameter to enforce dm-verity against the root filesystem. This reduces the need for an additional component (and increases boot performance).

The new, verity-related arguments for the `dm-mod.create` kernel parameter are read from a new, optional shim configuration field called `kernel_verity_params`.

This PR also shifts the two NVIDIA runtime classes to use a dm-verity protected image. For this, parts of the build logics are extended to 'namespace' the root hash files being generated for the different image build variants against which we aim to enforce dm-verity.

The following is an example of values in the new configuration:
```
/opt/kata/share/defaults/kata-containers/configuration-qemu-coco-dev.toml:kernel_verity_params = "root_hash=6020d57923e7104d16d2e9dfee6a54a9d6e72e2e9658033fa461601804de0b2a,salt=e8e3930e96361fcb69681fa052b8e39a032adc126ecfb2e9b5dd849f40c92214,data_blocks=96512,data_block_size=4096,hash_block_size=4096"
```

With this information and with the `kernel_params` field, the shims derive the final kernel command line parameters. An example for the verity part including the root filesystem related parameters is:
```
dm-mod.create=\"dm-verity,,,ro,0 772096 verity 1 /dev/vda1 /dev/vda2 4096 4096 96512 0 sha256 6020d57923e7104d16d2e9dfee6a54a9d6e72e2e9658033fa461601804de0b2a e8e3930e96361fcb69681fa052b8e39a032adc126ecfb2e9b5dd849f40c92214\" root=/dev/dm-0 rootflags=data=ordered,errors=remount-ro ro rootfstype=ext4
```

When the pod VM comes up we will see:
```
...
[    2.698390] device-mapper: verity: sha256 using \"sha256-lib\"
...
[    2.698647] device-mapper: ioctl: dm-0 (dm-verity) is ready
...
```
and when the parameter is changed erroneously:
```
...
[    2.412724] device-mapper: verity: 254:1: metadata block 0 is corrupted
...
```

An non-goal of this changeset was to merge the verity parameters into the `kernel_params` field. Without doing this, no cumbersome escape logic is required as we do not need to pass the `dm-mod.create="..."` parameter directly in the kernel_parameters, but only relevant dm-verity parameters in semi-structured manner (see above). The only place where the final command line is assembled is in the shims. Further, this is a line easy to comment out for developers to disable dm-verity enforcement (or for CI tasks).

Credits: these changes build on an existing work stream from @danmihai1 (https://github.com/kata-containers/kata-containers/pull/10688) and on existing work in the Microsoft fork of the kata-containers repository (`release/3.15.0` branch).

The following details slightly pod startup performance increases on a local machine using the `kata-qemu-coco-dev` runtime class, and using `systemd_analyze` in a `debug_console` with `enable_debug` with a simple pod manifest. Before the changes:
```
Startup finished in 170ms (kernel) + 276ms (userspace) = 447ms
Startup finished in 170ms (kernel) + 275ms (userspace) = 446ms
Startup finished in 180ms (kernel) + 271ms (userspace) = 452ms
Startup finished in 170ms (kernel) + 267ms (userspace) = 437ms
```
After the changes:
```
Startup finished in 135ms (kernel) + 256ms (userspace) = 392ms
Startup finished in 139ms (kernel) + 272ms (userspace) = 411ms
Startup finished in 144ms (kernel) + 270ms (userspace) = 415ms
Startup finished in 146ms (kernel) + 249ms (userspace) = 395ms
```

Also, this PR:
Fixes: #10959

### CODE REVIEW

**Comment by mythi** [comment]
> * replace the existing initramfs mode. Similar to other feature changes in this project, introducing a new mode and as it matures, we can decide to deprecate the initramfs mode in case it finds wide adoption

My 2 cents is that we don't have to offer options in this case since it's transparent to the users. Do you have concerns that this would be less mature somehow or would break existing users? 

I see this change just as a normal improvement to the stack. In fact, it would be nice to see the impact to boot-time for example: `systemd-analyze` from the debug console might give some additional justifications for the change.

**Comment by fidencio** [comment]
> My 2 cents is that we don't have to offer options in this case since it's transparent to the users. Do you have concerns that this would be less mature somehow or would break existing users?

I'm with Mikko on this one!

File: tools/osbuilder/image-builder/image_builder.sh [hunk 1]
```diff
@@ -23,6 +23,7 @@ ARCH=${ARCH:-$(uname -m)}
 [ "${TARGET_ARCH}" == "aarch64" ] && TARGET_ARCH=arm64
 TARGET_OS=${TARGET_OS:-linux}
 [ "${CROSS_BUILD}" == "true" ] && BUILDX=buildx && PLATFORM="--platform=${TARGET_OS}/${TARGET_ARCH}"
+VARIANT=${VARIANT:-}
```
Comment (danmihai1) [inline tools/osbuilder/image-builder/image_builder.sh]: Should VARIANT be renamed to IMAGE_TYPE_VARIANT or similar, to avoid hypothetical collisions with other types of VARIANTs?

File: tools/osbuilder/image-builder/image_builder.sh [hunk 2]
```diff
@@ -484,10 +487,57 @@ create_rootfs_image() {
...
 		local image_dir=$(dirname "${image}")
-		veritysetup format "${device}p1" "${device}p2" > "${image_dir}"/root_hash.txt 2>&1
+		local verity_output
+		if [ "${measured_rootfs_mode}" == "kernelinit" ]; then
+			verity_output=$(veritysetup format --no-superblock "${device}p1" "${device}p2" 2>&1)
+		else
+			verity_output=$(veritysetup format "${device}p1" "${device}p2" 2>&1)
+		fi
+		build_kernel_verity_params() {
+			local mode="$1"
```
Comment (danmihai1) [inline tools/osbuilder/image-builder/image_builder.sh]: I suggest "local -r" where practical.

But "local -r" was not being used in this script before, so postponing my suggestion seems reasonable too.

File: tools/osbuilder/image-builder/image_builder.sh [hunk 3]
```diff
@@ -484,10 +487,57 @@ create_rootfs_image() {
...
+				"${salt}" \
+				"${data_blocks}" \
+				"${data_block_size}" \
+				"${hash_block_size}"
+		}
+
+		local kernel_verity_params
+		kernel_verity_params="$(build_kernel_verity_params "${measured_rootfs_mode}" "${verity_output}")"
+
+		printf '%s\n' "${kernel_verity_params}" > "${image_dir}"/root_hash_${VARIANT}.txt
```
Comment (danmihai1) [inline tools/osbuilder/image-builder/image_builder.sh]: Suggest cleaning up some of the new warnings from https://github.com/kata-containers/kata-containers/actions/runs/21407887966/job/61636725764?pr=12396

File: tools/osbuilder/rootfs-builder/ubuntu/config.sh [hunk 4]
```diff
@@ -8,9 +8,12 @@ OS_NAME=ubuntu
 # This should be Ubuntu's code name, e.g. "focal" (Focal Fossa) for 20.04
 OS_VERSION=${OS_VERSION:-""}
 [ -z "$OS_VERSION" ] && echo "OS_VERSION is required, but was not set" && exit 1
+MEASURED_ROOTFS_MODE=${MEASURED_ROOTFS_MODE:-}
 PACKAGES="chrony iptables dbus"
 [ "$AGENT_INIT" = no ] && PACKAGES+=" init"
-[ "$MEASURED_ROOTFS" = yes ] && PACKAGES+=" cryptsetup-bin e2fsprogs"
+if [ "${MEASURED_ROOTFS_MODE}" = "initramfs" ] || [ "${MEASURED_ROOTFS_MODE}" = "kernelinit" ]; then
+	PACKAGES+=" cryptsetup-bin e2fsprogs"
```
Comment (danmihai1) [inline tools/osbuilder/rootfs-builder/ubuntu/config.sh]: If I remember correctly, these two packages are not required for the new kernelinit.

File: .github/workflows/build-kata-static-tarball-amd64.yaml [hunk 5]
```diff
@@ -312,7 +312,7 @@ jobs:
           ARTEFACT_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
           TARGET_BRANCH: ${{ inputs.target-branch }}
           RELEASE: ${{ inputs.stage == 'release' && 'yes' || 'no' }}
-          MEASURED_ROOTFS: yes
+          MEASURED_ROOTFS_MODE: initramfs
```
Comment (danmihai1) [inline .github/workflows/build-kata-static-tarball-amd64.yaml]: Please consider the possibility of breaking the "rootfs: runtime: Introduce kernelinit verity mode" commit into a few smaller commits, to make PR reviews easier. But, since you already tested the current, larger, commit, I won't hold it against you if you'll decide to keep this commit.

Ideas of possible smaller commit boundaries:

1. Add ability to produce kernelinit information, at build time.
2. Add ability to consume kernelinit information in runtime-go.
3. Add ability to consume kernelinit information in runtime-rs.
4. Enable producing kernelinit information for the NVIDIA image files.

**Review by danmihai1 — APPROVED** [review]
Thanks @manuelh-dev !

File: tools/osbuilder/rootfs-builder/ubuntu/config.sh (hunk 4 above)
Comment (manuelh-dev) [reply tools/osbuilder/rootfs-builder/ubuntu/config.sh]: Interesting design, actually, looks like the initrd builder is used to build the initramfs for dm-verity using PACKAGES ... so, using the same mechanism and variables if building an initrd.

File: tools/packaging/static-build/shim-v2/build.sh [hunk 6]
```diff
@@ -36,18 +36,31 @@ case "${RUNTIME_CHOICE}" in
...
+	root_hash_file="${root_hash_dir}/root_hash_${variant}.txt"
+	[ -f "$root_hash_file" ] || continue
+
+	# root_hash_*.txt contains a single kernel_verity_params line.
+	IFS= read -r root_measure_config < "${root_hash_file}"
+	root_measure_config="${root_measure_config%$'\r'}"
+	[ -n "${root_measure_config}" ] || die "Empty kernel verity params in ${root_hash_file}"
+
+	EXTRA_OPTS+=" ${param_var}=${root_measure_config}"
+done
```
[the remark this answers is not in the document]
Comment (manuelh-dev) [reply tools/packaging/static-build/shim-v2/build.sh:63]: This problem existed before already with root_hash.txt. I won't be solving this as part of this PR, but this is a valid consideration.

File: .github/workflows/build-kata-static-tarball-amd64.yaml (hunk 5 above)
Comment (manuelh-dev) [reply .github/workflows/build-kata-static-tarball-amd64.yaml]: Thank you, updated in the new revision in quite similar manner as suggested

File: tools/osbuilder/image-builder/image_builder.sh (hunk 1 above)
Comment (manuelh-dev) [reply tools/osbuilder/image-builder/image_builder.sh]: renamed to BUILD_VARIANT. This variable is used across a few places, and it does not necessarily indicate `image` (just in the context of the dm-verity path, it does, but it's also used in the NVIDIA rootfs scripts).

File: tools/osbuilder/image-builder/image_builder.sh (hunk 2 above)
Comment (manuelh-dev) [reply tools/osbuilder/image-builder/image_builder.sh]: done, along with changes for shellcheck to pass

**Comment by manuelh-dev** [comment]
> > My 2 cents is that we don't have to offer options in this case since it's transparent to the users. Do you have concerns that this would be less mature somehow or would break existing users?
> 
> I'm with Mikko on this one!

Thank you! No concerns on my end as long as the users of `configuration-qemu-coco-dev.toml` and `configuration-qemu-tdx.toml` have no concerns with that (and if  nobody else had plans with that initramfs, e.g., baking other things in).

Next steps:
- Test CI paths with kernelinit for these two configurations
- Try to acquire some statistics, e.g., `systemd-analyze` for the `configuration-qemu-coco-dev.toml` handler which I am able to run locally and which should have systemd.
- Tentatively, add a commit to remove the initramfs option, getting us back to from `MEASURED_ROOTFS_MODE: none/initramfs/kernelinit` to `MEASURED_ROOTFS: yes|no`.

**Comment by manuelh-dev** [comment]
@mythi - added some measurements for boot performance to the bottom of the PR description. We're indeed seeing slight decreases in boot time.

**Comment by mythi** [comment]
> @mythi - added some measurements for boot performance to the bottom of the PR description. We're indeed seeing slight decreases in boot time.

thanks!

**Comment by manuelh-dev** [comment]
@danmihai1 @mythi @Apokleos @fidencio - I am moving this PR out of draft state. kernelinit is now the only supported dm-verity path. I have removed the initramfs component.

Other noteworthy changes: Adjusted the measured rootfs test case and enabled overwriting `kernel_verity_params` via annotations.

**Comment by mythi** [comment]
> @danmihai1 @mythi @Apokleos @fidencio - I am moving this PR out of draft state. kernelinit is now the only supported dm-verity path. I have removed the initramfs component.

Do you plan to squash the commits after the first round of reviews? I think the intermediate initramfs/kernelinit mode is not necessary. Also it seems commit ec45f31 can be dropped.

Other topics:
- can we get the whitespace cleanups to another PR. 
- I could not find arguments in the commit messages why a separate config entry is needed
- the cover letter explaining the boot time improvement is great but this could also be covered by one of the commits (with a summary of "this improves by 9-10%")

You may also set Fixes: #10959. The core problem of this was the kernel builtin initramfs (although we never found the reason why it happens).

**Comment by manuelh-dev** [comment]
> > @danmihai1 @mythi @Apokleos @fidencio - I am moving this PR out of draft state. kernelinit is now the only supported dm-verity path. I have removed the initramfs component.
> 
> Do you plan to squash the commits after the first round of reviews? I think the intermediate initramfs/kernelinit mode is not necessary. Also it seems commit [ec45f31](https://github.com/kata-containers/kata-containers/commit/ec45f31116cdb7b87e496429da5d72d6afe65c97) can be dropped.
> 
> Other topics:
> 
> * can we get the whitespace cleanups to another PR.
> * I could not find arguments in the commit messages why a separate config entry is needed
> * the cover letter explaining the boot time improvement is great but this could also be covered by one of the commits (with a summary of "this improves by 9-10%")
> 
> You may also set Fixes: #10959. The core problem of this was the kernel builtin initramfs (although we never found the reason why it happens).

Agree with being able to squash commits and being able to remove commit [ec45f31](https://github.com/kata-containers/kata-containers/commit/ec45f31116cdb7b87e496429da5d72d6afe65c97) as a result. However: my thought was that it would be kind of nice to have a git history in the main branch with a functional version which supports initramfs and kernelinit mode, in case an initramfs becomes of use for anyone. In case that is not best (i.e., bad) practice or adds zero value, happy to squash things.

Ack on all others - thank you, these are very good points, will do.

**Comment by manuelh-dev** [comment]
Explanation on measurements and rational to introduce `kernel_verity_params` is now in `22617a3423ac2716b04fa3c6706844f981bb1508`. For the trailing whitespaces in the shim configs, created: https://github.com/kata-containers/kata-containers/pull/12433

I will rebase this this PR once/if we get quorum with 12433.

File: tools/osbuilder/rootfs-builder/ubuntu/config.sh [hunk 7]
```diff
@@ -10,7 +10,6 @@ OS_VERSION=${OS_VERSION:-""}
 [ -z "$OS_VERSION" ] && echo "OS_VERSION is required, but was not set" && exit 1
 PACKAGES="chrony iptables dbus"
 [ "$AGENT_INIT" = no ] && PACKAGES+=" init"
-[ "$MEASURED_ROOTFS" = yes ] && PACKAGES+=" cryptsetup-bin e2fsprogs"
```
Comment (manuelh-dev) [inline tools/osbuilder/rootfs-builder/ubuntu/config.sh:13]: @stevenhorsman @mythi @fidencio @fitzthum - could you do me a favor and see if you remember or know relevant people to tag if you are interested in this and if you have a minute?

This is an interesting line regardless of this PR here - I just realized that without this line, the CDH container image layer storage feature breaks as the root filesystem is missing the `cryptsetup` binary.

This, to me, is kind of unfortunate. The line controls both what goes into the dm-verity initramfs and what goes into the UVM rootfs (both use the same distro config).

This means, the CDH trusted_storage feature is only working because we build e.g. the qemu-coco-dev runtime class with MEASURED_ROOTFS=yes.

Maybe that was the logical intent, saying that using the CDH storage feature only makes sense for guests with dm-verity enabled, but this was not clear to me. In my PR I have removed this line as I was under the assumption we wouldn't need these binaries anymore because my PR removes the need for the kernel initramfs for verity.

In my  PR, I would bring this condition back with something like:
```
# CDH secure storage implementation using luks-encrypt-storage script requires these tools in the guest.
[[ "${CONFIDENTIAL_GUEST:-no}" = "yes" ]] && PACKAGES+=" cryptsetup-bin dmsetup e2fsprogs"
```
This way the intent is more clear.

Regardless of my PR, this should have rather been a condition like 'if CONFIDENTIAL_GUEST or MEASURED_ROOTFS' to avoid such dependencies. Maybe even better would have been to declare a new variable which indicates whether the trusted storage feature is used or not (in theory, a non-confidential guest could use it too).

Maybe I am missing things, but I want to bring this up because we may have more such 'dangerous' uses of variables.

Comment (mythi) [reply tools/osbuilder/rootfs-builder/ubuntu/config.sh:13]: @manuelh-dev good catch, I don't think you are missing anything and changing `MEASURED_ROOTFS` to `CONFIDENTIAL_GUEST` sounds like the right fix.

31c0ad2076 was in the very early stages of CoCo builds and CDH did not even exist back then.

**Comment by manuelh-dev** [comment]
> Explanation on measurements and rational to introduce `kernel_verity_params` is now in `22617a3423ac2716b04fa3c6706844f981bb1508`. For the trailing whitespaces in the shim configs, created: #12433
> 
> I will rebase this this PR once/if we get quorum with 12433.

@mythi - rebased onto upstream/main, the config changes are now sanitized in this pull request

File: tools/osbuilder/rootfs-builder/ubuntu/config.sh [hunk 8]
```diff
@@ -8,12 +8,10 @@ OS_NAME=ubuntu
...
 OS_VERSION=${OS_VERSION:-""}
 [ -z "$OS_VERSION" ] && echo "OS_VERSION is required, but was not set" && exit 1
-MEASURED_ROOTFS_MODE=${MEASURED_ROOTFS_MODE:-}
 PACKAGES="chrony iptables dbus"
 [ "$AGENT_INIT" = no ] && PACKAGES+=" init"
-if [[ "${MEASURED_ROOTFS_MODE}" = "initramfs" ]]; then
-	PACKAGES+=" cryptsetup-bin e2fsprogs"
-fi
+# CDH secure storage feature requires these tools in the guest
+[[ "${CONFIDENTIAL_GUEST:-no}" = "yes" ]] && PACKAGES+=" cryptsetup-bin dmsetup e2fsprogs"
```
Comment (mythi) [inline tools/osbuilder/rootfs-builder/ubuntu/config.sh]: nit: `config.sh` changes  could be a commit of its own.

**Review by mythi — APPROVED** [review]
LGTM. One minor nit.

File: tools/osbuilder/rootfs-builder/ubuntu/config.sh (hunk 8 above)
Comment (manuelh-dev) [reply tools/osbuilder/rootfs-builder/ubuntu/config.sh]: Agree, added 3e1065205f356c47e4f5b59942c61310f31cfc00 into the commit chain and rebased.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @manuelh-dev!
