### PR TITLE
runtime: also check kvm module `sev` parameter as bool

### LINKED ISSUE #3273: runtime: checking kvm_amd.sev parameter fail with recent Linux versions
# Description of problem

With recent linux kernel, the kvm module declares the sev parameters as a `boolean` (instead of an `int`).
This causes the runtime to fail verifying this parameter, even when the feature is actually active.

# Expected result

Runtime should consider both `1` and `Y` as valid values for the `kvm_amd.sev` parameter.

# Actual result

Runtime check fails with `Y`.

### PR DESCRIPTION
**Pull request by pete842**
Since linux 5.12, `kvm` module declares the `sev` parameters as a `boolean` (instead of an `int`) .

This PR fixes the verification of this parameter made by the runtime for linux 5.12 and above.

This was successfully tested against linux 5.15.

Edit:
Fixes #3273
Signed-off-by: Pierre Kohler <pierre.kohler@cysec.systems>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
@pete842 thank you for your PR, content looks fine. You will need to link an issue in the commit (e.g. `Fixes: #xxx`), have a body, and sign off your messages (`git commit -s`). I'm going to call this a "no backport required" since we're still officially on 5.10, but please tell me if you disagree. /cc @fitzthum

**Comment by fitzthum** [comment]
LGTM. I think @jimcadden has made an identical change as part of his shim patches.

**Comment by Jakob-Naucke** [comment]
Oh, and @pete842 I forgot to mention: this needs a rebase.

**Review by fitzthum — APPROVED** [review]
LGTM. We ran into this issue as well. I think @jimcadden has an identical patch as part of his shim PR. Good to have it go directly to `main` tho.

**Comment by jimcadden** [comment]
> LGTM. I think @jimcadden has made an identical change as part of his tentative shim patches.

Yes, same change. I will rebase off this once merged

**Comment by liubin** [comment]
Hi, @pete842 thank you for this PR, I closed this PR once and reopened it to trigger the CI, it will not affect the review of this PR.
/test

**Review by amshinde — DISMISSED** [review]

**Comment by Jakob-Naucke** [comment]
@pete842 please rebase :)

**Comment by pete842** [comment]
@Jakob-Naucke it will be done within the next 8 hours, sorry for the delay.

**Review by jodh-intel — APPROVED** [review]

**Comment by jodh-intel** [comment]
Restarted the aborted static checks. If they succeed, this should be good to land...

**Comment by jodh-intel** [comment]
@pete842 - Please can you try rebasing as the CI static checks are failing for a file you haven't modified:

```
[static-checks.sh:1244] INFO: Checking Dockerfile 'ci/openshift-ci/images/Dockerfile.buildroot'
ci/openshift-ci/images/Dockerfile.buildroot:9 DL3032 warning: `yum clean all` missing after yum command.
Error: Process completed with exit code 2.
```

/cc @wainersm who added the dockerfile checker.

**Comment by pete842** [comment]
Rebased again (and lost approvals).

**Comment by fidencio** [comment]
> Rebased again (and lost approvals).

That's expected.  This was a discussion that happened on Yesterday's architecture committee meeting and a change we've done on all our repos.  It's been tracked here: https://github.com/kata-containers/community/issues/249

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by pete842** [comment]
Duly noted @fidencio, sorry for the inconvenience!
I really thought I was helping keeping things fast and easy by being proactive and rebasing on my own initiative.

That said, I have no problem on waiting to be asked for a rebase by maintainers when its time.

Again, my apology to the reviewers and other people that have to check on those changes one more time.

Now, as per your request, could @jodh-intel, @amshinde, @fitzthum give an other look to this PR?
I have no changes to notifiy, this was a simple alignment to the main branch.

**Review by fitzthum — APPROVED** [review]

File: src/runtime/virtcontainers/hypervisor_amd64.go [hunk 1]
```diff
@@ -18,9 +18,9 @@ func availableGuestProtection() (guestProtection, error) {
 	if d, err := os.Stat(tdxSysFirmwareDir); (err == nil && d.IsDir()) || flags[tdxCPUFlag] {
 		return tdxProtection, nil
 	}
-	// SEV is supported and enabled when the kvm module `sev` parameter is set to `1`
+	// SEV is supported and enabled when the kvm module `sev` parameter is set to `1` (or `Y` for linux >= 5.12)
 	if _, err := os.Stat(sevKvmParameterPath); err == nil {
-		if c, err := os.ReadFile(sevKvmParameterPath); err == nil && len(c) > 0 && c[0] == '1' {
+		if c, err := os.ReadFile(sevKvmParameterPath); err == nil && len(c) > 0 && (c[0] == '1' || c[0] == 'Y') {
```
Comment (larrydewey) [inline src/runtime/virtcontainers/hypervisor_amd64.go:23]: Depending on where this is looking, it would be wise to normalize the string here. I have seen different case usage in different distributions.

**Review by jodh-intel — APPROVED** [review]
Thanks @pete842.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @pete842!
