### PR TITLE
runtime-rs: enhance debug info for agent connect.

### LINKED ISSUE #10057: Enhance: we need more friendly logs for debugging agent conntion cases
As the title description, we need dump more useful and friendly logs when kata pods fail.

### PR DESCRIPTION
**Pull request by Apokleos**
we need more friendly logs for debugging agent conntion cases when kata pods fail.

Fixes #10057

### CODE REVIEW

**Comment by Apokleos** [comment]
Hi @lifupan @ananos I create a PR and expect it to help give us more useful info when agent connection fails.  PTAL. Thx

**Review by ananos — APPROVED** [review]
thanks @Apokleos, looks good!

File: src/runtime-rs/crates/agent/src/sock/vsock.rs [hunk 1]
```diff
@@ -69,11 +69,15 @@ impl Sock for Vsock {
                     );
                     return Ok(Stream::Vsock(stream));
                 }
-                Err(_) => {
+                Err(e) => {
+                    debug!(sl!(), "connect vsock failed on {} with error : {:?}", i, e);
```
Comment (justxuewei) [inline src/runtime-rs/crates/agent/src/sock/vsock.rs:73]: Add some words about retry? For example: `"retry after {} ms: failed to connect to agent via vsock at {} attempts: {:?}", onfig.dial_timeout_ms, i, e`.

**Review by justxuewei — APPROVED** [review]
Lgtm, except for a nit ;)
