### PR TITLE
runtime: Fix stdout/stderr output from container being truncated

### LINKED ISSUE #1713: Logs output on Kata Containers pod is being truncated
# Description of problem

When printing the logs from a Kata Container, the logs content ends up being truncated, which doesn't happen with vanilla containers.

vanilla.yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: test-vanilla
spec:
  restartPolicy: Never
  containers:
  - name: "test-vanilla"
    image: "fedora:latest"
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "cat /etc/services 1>&2"
```
kata.yaml:
```
--- 
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
spec:
  restartPolicy: Never
  runtimeClassName: "kata"
  containers:
  - name: "test-kata"
    image: "fedora:latest"
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "cat /etc/services 1>&2"
```

In order to reproduce the issue, simply create those two pods:
```
kubectl create -f vanilla.yaml
kubectl create -f --kata.yaml
```

Then wait till the pods are completed;
Finally, compare the outputs:

```
kubectl logs test-vanilla | wc -l
kubectl logs test-kata | wc -l
kubectl logs test-vanilla | tail
kubectl logs test-kata | tail
```

# Expected result
The outputs should be the same.

# Actual result
Sometimes (about 1 out of 3), the logs from the test-kata pod are truncated.
The amount of missing data is not always the same.

### PR DESCRIPTION
**Pull request by littlejawa**
Do not close the tty as part of the stdout redirection routine.
The close is already happening a couple lines below, after all routines
have finished.

Fixes #1713

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@littlejawa, firstly, thanks for the contribution!

I'm wondering how hard was to reproduce this with a really huge file.  If we could have a reproducer for this as part of https://github.com/kata-containers/tests/tree/main/integration/kubernetes, that would be amazing!
/cc @wainersm as he can help!

**Comment by littlejawa** [comment]
@fidencio I can certainly try.
So far, I only have a very hard-coded/specific script to help reproduce, but it probably can be improved.
I'll have a look, but any guidance is welcome :-)

File: src/runtime/containerd-shim-v2/stream.go [hunk 1]
```diff
@@ -109,7 +109,6 @@ func ioCopy(exitch, stdinCloser chan struct{}, tty *ttyIO, stdinPipe io.WriteClo
 			defer bufPool.Put(p)
 			io.CopyBuffer(tty.Stdout, stdoutPipe, *p)
 			wg.Done()
-			closeOnce.Do(tty.close)
```
Comment (lifupan) [inline src/runtime/containerd-shim-v2/stream.go:112]: You can't  delete this tty close, since it will close the tty's stdin and then the following wg.Wait() can continue, otherwise, the stdin iocopy wouldn't ended and there's a dead lock occur.  The root issue here is that it shouldn't close the tty's stderr at the end of the stdout iocopy, so in addition to delete "closeOnce.Do(tty.close)",  you should also close the tty's stdin here.

Comment (littlejawa) [reply src/runtime/containerd-shim-v2/stream.go:112]: Right. In my tests, stdin was nil so the routine was not started, and I couldn't see this deadlock.
I will change that. Thanks!

**Comment by littlejawa** [comment]
@lifupan : modified as asked.
I also removed the call to sync.Once as we're now calling tty.close() only once anyway, so no synchronization is needed - am I right?

**Comment by lifupan** [comment]
> @lifupan : modified as asked.
> I also removed the call to sync.Once as we're now calling tty.close() only once anyway, so no synchronization is needed - am I right?

Hi @littlejawa 

You are right, thanks. It LGTM.

**Review by lifupan — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @littlejawa!
