### PR TITLE
runtime-rs: Empty block-rootfs Storage.options and align with Go runtime

### LINKED ISSUE #11688: [runtime-rs] Block rootfs mount fails with `EINVAL` when SELinux label options are propagated to guest `Storage.options`
## Description
With SELinux enabled (permissive) and containerd using the devmapper snapshotter (`ext4`), the Go runtime boots fine (QEMU), but **runtime-rs** fails to mount a **block rootfs** with `EINVAL`.

Root cause: **runtime-rs clones the host rootfs mount options into the guest `Storage.options`**, which can include SELinux label options (e.g., `context=`, `fscontext=`, `defcontext=`, `rootcontext=`, `seclabel`). These are valid on the host but are **unknown/invalid in the guest**, causing `mount(2)` to return `EINVAL`.

In contrast, the Go runtime leaves `Storage.options` empty for block devices (except `xfs` → `nouuid`), so it does not leak SELinux options into the guest.

---

## Environment

- **SELinux**
  ```
  SELinux status: enabled
  Current mode:   permissive
  Policy MLS:     enabled
  ```
- **containerd config (relevant)**
  ```toml
  [plugins."io.containerd.grpc.v1.cri".containerd]
    default_runtime_name = "runc"
    snapshotter = "devmapper"

  [plugins."io.containerd.snapshotter.v1.devmapper"]
    async_remove = false
    base_image_size = "10GB"
    discard_blocks = true
    fs_options = ""
    fs_type = "ext4"
    pool_name = "devpool"
    root_path = "/var/lib/containerd/devmapper"
  ```

---

## Repro Steps

1) Sandbox spec (SELinux labels present):

**sandbox.yaml**
```yaml
metadata:
  attempt: 1
  name: test-pod1
  namespace: default
  uid: hdishd83djaidwnduwk28bcsb
log_directory: /tmp
```

2) Run:
```bash
sudo crictl runp -r kata sandbox.yaml
```

3) Result (runtime-rs):
```
failed to mount /dev/vda to /run/kata-containers/shared/containers/passthrough/<cid>/rootfs, with error: EINVAL: Invalid argument
```

(Go runtime succeeds under the same setup.)

---

## Observed vs Expected

- **Observed (runtime-rs):** Block rootfs mount of `/dev/vda` fails with `EINVAL`.
- **Expected:** Block rootfs should mount successfully (matches Go runtime behavior).

---

## Root Cause Analysis

- **Go runtime (works)** — `src/runtime/virtcontainers/fs_share_linux.go` (`ShareRootFilesystem`):
  ```go
  rootfsStorage.Fstype = c.state.Fstype
  if c.state.Fstype == "xfs" {
      rootfsStorage.Options = []string{"nouuid"}
  }
  // Otherwise, Options remain nil/empty for block devices
  ```

- **runtime-rs (fails)** — `src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs`:
  ```rust
  let mut storage = Storage {
      fs_type: rootfs.fs_type.clone(),
      mount_point: container_path.clone(),
      options: rootfs.options.clone(), // ← clones host options, including SELinux labels
      ..Default::default()
  };
  ```

Because SELinux labels from the host (via OCI/CRI SELinux settings) are copied into the guest `Storage.options`, the guest kernel rejects those options during `mount(2)` with `EINVAL`.

---

### PR DESCRIPTION
**Pull request by Caspian443**
- Set guest Storage.options for block rootfs to empty (do not propagate host mount options).
- Align behavior with Go runtime: only add xfs "nouuid" when needed.

Fixes #11688

### CODE REVIEW

File: src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs [hunk 1]
```diff
@@ -67,10 +67,14 @@ impl BlockRootfs {
         let mut storage = Storage {
             fs_type: rootfs.fs_type.clone(),
             mount_point: container_path.clone(),
-            options: rootfs.options.clone(),
+            options: vec![],
             ..Default::default()
         };
 
+        if rootfs.fs_type == "xfs" {
```
Comment (Caspian443) [inline src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs]: It is to align the handling of the XFS type filesystem with the Go version of the runtime.

**Comment by xavier-niu** [comment]
Hey @Caspian443, please format your commit message with proper line breaks.

```
runtime-rs: Empty block-rootfs Storage.options and align with Go runtime
<line break>
- Set guest Storage.options for block rootfs to empty (do not propagate host mount options).
- Align behavior with Go runtime: only add xfs "nouuid" when needed.
<line break>
Signed-off-by: Caspian443 <scrisis843@gmail.com>
```

File: src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (xavier-niu) [reply src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs]: Use `VM_ROOTFS_FILESYSTEM_XFS`?

[the remark this answers is not in the document]
Comment (Caspian443) [reply src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs]: ok

File: src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs [hunk 2]
```diff
@@ -67,10 +68,14 @@ impl BlockRootfs {
         let mut storage = Storage {
             fs_type: rootfs.fs_type.clone(),
             mount_point: container_path.clone(),
-            options: rootfs.options.clone(),
+            options: vec![],
             ..Default::default()
         };
 
+        if rootfs.fs_type == VM_ROOTFS_FILESYSTEM_XFS {
```
Comment (Apokleos) [inline src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs:78]: Comments about its background are needed here.

Comment (xavier-niu) [reply src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs:78]: It is aimed to align with go version. However, there is no comments for these lines in the go. 🤦‍♂️

File: src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs [hunk 3]
```diff
@@ -25,6 +25,7 @@ use oci_spec::runtime as oci;
 use std::fs;
 use tokio::sync::RwLock;
 
+const VM_ROOTFS_FILESYSTEM_XFS: &str = "xfs";
```
Comment (xavier-niu) [inline src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs]: Can we move this, `VM_ROOTFS_FILESYSTEM_EXT4`, `VM_ROOTFS_FILESYSTEM_EROFS` from `hypervisor/libs` to `kata_types`? Create a `fs` mod in `kata_types`, and update  the references in the `hypervisor` that use these constants.

Comment (Caspian443) [reply src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs]: ok

File: src/libs/kata-types/src/fs.rs [hunk 4]
```diff
@@ -0,0 +1,15 @@
+// Copyright (c) 2025
```
Comment (Apokleos) [inline src/libs/kata-types/src/fs.rs]: The full "Copyright" is needed here !
```
// Copyright 2025 Kata Contributors
//
// SPDX-License-Identifier: Apache-2.0
//
```

File: src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs (hunk 2 above)
Comment (Apokleos) [reply src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs:78]: It's a special case in the workflow, just the code might confuse other people why do so. And with this case without comment within runtime-go, I don't think we should keep aligned with it.

File: src/libs/kata-types/src/fs.rs (hunk 4 above)
Comment (Caspian443) [reply src/libs/kata-types/src/fs.rs]: Thanks for the review! I’ve addressed both comments:

1. Updated the header in src/libs/kata-types/src/fs.rs to “Copyright 2025 Kata Contributors” and kept the SPDX line.
2. Added a brief comment for the newly added xfs type and clarified why we pass nouuid when mounting an XFS rootfs (to avoid UUID conflicts).
