### PR TITLE
test: Add a unit test for ioCopy()

### LINKED ISSUE #1831: Add a unit test for ioCopy()
Following the fix for #1713 - need to add a unit test that verify there is no regression on ioCopy()

### PR DESCRIPTION
**Pull request by littlejawa**
Following the fix for #1713, adding a unit test for ioCopy() that
verifies that data is properly copied from source to destination
whatever the order in which the pipes are closed.

Fixes #1831

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

File: src/runtime/containerd-shim-v2/stream_test.go [hunk 1]
```diff
@@ -89,3 +89,189 @@ func TestNewTtyIOFifoReopen(t *testing.T) {
...
+			return nil, nil
+		}
+
+		firstR, firstW = getPipes(first)
+		secondR, secondW = getPipes(second)
+		thirdR, thirdW = getPipes(third)
+
+		checkFifoWrite := func(w io.Writer, b []byte, name string) {
+			_, err := w.Write(b)
+			if name == "in" && (name == third || name == second && first == "out") {
```
Comment (jodh-intel) [inline src/runtime/containerd-shim-v2/stream_test.go:198]: But where's the ["shake it all about"](https://en.wikipedia.org/wiki/Hokey_Cokey) check? :smile:

**Review by jodh-intel — APPROVED** [review]
Nice! Thanks @littlejawa.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, and these are the results of the local tests:
* with your fix:
```
INFO: running as actual user 1000 (effective 1000), actual group 1000 (effective 1000)
INFO: switching to fake virtcontainers implementation for testing
INFO: creating test directory
INFO: test directory is /tmp/shimV2-060847818
INFO: checking for container engine: docker
INFO: checking for container engine: podman
INFO: ensuring required container image (busybox) is available
INFO: container image busybox already exists locally
INFO: creating OCI bundle in /tmp/shimV2-060847818/bundle for tests to use
=== RUN   TestIoCopy
--- PASS: TestIoCopy (20.02s)
PASS
ok  	github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2	21.103s
```

* reverting your fix:
```
INFO: running as actual user 1000 (effective 1000), actual group 1000 (effective 1000)
INFO: switching to fake virtcontainers implementation for testing
INFO: creating test directory
INFO: test directory is /tmp/shimV2-362679642
INFO: checking for container engine: docker
INFO: checking for container engine: podman
INFO: ensuring required container image (busybox) is available
INFO: container image busybox already exists locally
INFO: creating OCI bundle in /tmp/shimV2-362679642/bundle for tests to use
=== RUN   TestIoCopy
    stream_test.go:216: 
        	Error Trace:	stream_test.go:216
        	            				stream_test.go:255
        	            				stream_test.go:267
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out err ] - Error reading from stderr
    stream_test.go:217: 
        	Error Trace:	stream_test.go:217
        	            				stream_test.go:255
        	            				stream_test.go:267
        	Error:      	Not equal: 
        	            	expected: []byte{0x54, 0x65, 0x73, 0x74, 0x32}
        	            	actual  : []byte{0x0, 0x0, 0x0, 0x0, 0x0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 ([]uint8) (len=5) {
        	            	- 00000000  54 65 73 74 32                                    |Test2|
        	            	+ 00000000  00 00 00 00 00                                    |.....|
        	            	 }
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out err ] - Value mismatch on stderr
    stream_test.go:216: 
        	Error Trace:	stream_test.go:216
        	            				stream_test.go:255
        	            				stream_test.go:271
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out err in] - Error reading from stderr
    stream_test.go:217: 
        	Error Trace:	stream_test.go:217
        	            				stream_test.go:255
        	            				stream_test.go:271
        	Error:      	Not equal: 
        	            	expected: []byte{0x54, 0x65, 0x73, 0x74, 0x32}
        	            	actual  : []byte{0x0, 0x0, 0x0, 0x0, 0x0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 ([]uint8) (len=5) {
        	            	- 00000000  54 65 73 74 32                                    |Test2|
        	            	+ 00000000  00 00 00 00 00                                    |.....|
        	            	 }
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out err in] - Value mismatch on stderr
    stream_test.go:216: 
        	Error Trace:	stream_test.go:216
        	            				stream_test.go:257
        	            				stream_test.go:272
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out in err] - Error reading from stderr
    stream_test.go:217: 
        	Error Trace:	stream_test.go:217
        	            				stream_test.go:257
        	            				stream_test.go:272
        	Error:      	Not equal: 
        	            	expected: []byte{0x54, 0x65, 0x73, 0x74, 0x33}
        	            	actual  : []byte{0x0, 0x0, 0x0, 0x0, 0x0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 ([]uint8) (len=5) {
        	            	- 00000000  54 65 73 74 33                                    |Test3|
        	            	+ 00000000  00 00 00 00 00                                    |.....|
        	            	 }
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [out in err] - Value mismatch on stderr
    stream_test.go:216: 
        	Error Trace:	stream_test.go:216
        	            				stream_test.go:257
        	            				stream_test.go:275
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [in out err] - Error reading from stderr
    stream_test.go:217: 
        	Error Trace:	stream_test.go:217
        	            				stream_test.go:257
        	            				stream_test.go:275
        	Error:      	Not equal: 
        	            	expected: []byte{0x54, 0x65, 0x73, 0x74, 0x33}
        	            	actual  : []byte{0x0, 0x0, 0x0, 0x0, 0x0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 ([]uint8) (len=5) {
        	            	- 00000000  54 65 73 74 33                                    |Test3|
        	            	+ 00000000  00 00 00 00 00                                    |.....|
        	            	 }
        	Test:       	TestIoCopy
        	Messages:   	Error found while using order [in out err] - Value mismatch on stderr
--- FAIL: TestIoCopy (20.02s)
FAIL
exit status 1
FAIL	github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2	20.605s
```

Thanks a lot for the patch, I'd like to see it backported to the stable-2.1 branch and sorry for the time it took for me to get to it.
