### PR TITLE
agent: Fix to parsing of /proc/self/mountinfo

### LINKED ISSUE #2182: Agent can mis-parse /proc/self/mountinfo if device for virt filesystems is "-"
# Description of problem

Currently, the agent can generate a bunch of "mountinfo corrupted!" warnings on what are actually perfectly valid /proc/self/mountinfo contents, because virtual filesystems happen to be mounted with an (arbitrary) device of `-`.

### PR DESCRIPTION
**Pull request by dgibson**
get_mounts() parses /proc/self/mountinfo in order to get the mountpoints
for various cgroup filesystems.  One of the entries in mountinfo is the
"device" for each filesystem, but for virtual filesystems like /proc, /sys
and cgroups, the device entry is arbitrary.  Depending on the exact rootfs
setup, it can end up being "-".

This breaks get_mounts() because it uses " - " as a separator.  There
really is a " - " separator in mountinfo, but in this case the device entry
shows up as a second one.  Fix this, by changing a split to a splitn, which
will effectively only consider the first " - " in the line.

While we're there, make the warning message more useful, by having it
actually show which line it wasn't able to parse.

fixes #2182

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

### CODE REVIEW

**Comment by dgibson** [comment]
@marcel-apf, FYI, filed this bug we found last night.

**Comment by egernst** [comment]
@mxpv ^^

**Comment by dgibson** [comment]
I'm pretty sure those CI failures aren't my change.
/retest

**Review by lifupan — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @dgibson and good catch!

For bonus points, how about adding a unit test with a few awkward entries by changing `get_mounts()` to `get_mounts(mountinfo: &str)` to allow it to be called as `get_mounts(MOUNTS)` by default but allow a tempfile to be passed in the unit test? :smile:

File: src/agent/rustjail/src/cgroups/fs/mod.rs [hunk 1]
```diff
@@ -923,12 +923,12 @@ pub fn get_mounts() -> Result<HashMap<String, String>> {
...
 
     for l in fs::read_to_string(MOUNTS)?.lines() {
-        let p: Vec<&str> = l.split(" - ").collect();
+        let p: Vec<&str> = l.splitn(2, " - ").collect();
         let pre: Vec<&str> = p[0].split(' ').collect();
         let post: Vec<&str> = p[1].split(' ').collect();
 
         if post.len() != 3 {
-            warn!(sl!(), "mountinfo corrupted!");
+            warn!(sl!(), "can't parse {} line {:?}", MOUNTS, l);
```
Comment (c3d) [inline src/agent/rustjail/src/cgroups/fs/mod.rs:931]: I find the new message a bit too generic, and I think we should not use contracted forms like "can't".

What about: "cannot extract mountpoint from {}, the line read was {:?}"?

**Review by c3d — APPROVED** [review]
Suggested a small rewording of the new warning. Otherwise looks good to me.

**Review by mxpv — APPROVED** [review]

File: src/agent/rustjail/src/cgroups/fs/mod.rs (hunk 1 above)
Comment (dgibson) [reply src/agent/rustjail/src/cgroups/fs/mod.rs:931]: Really, Christophe?  You're going to nitpick my error message when it's replacing `mountinfo corrupted!` with no further information?

I actually thing your suggested replacement is needlessly wordy, and not really accurate, since it's not specifically about extracting the mountpoint.  Avoiding contractions is generally recommended for formal writing, and I'd argue for error messages, succinctness is more important than formality.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @dgibson!

**Comment by dgibson** [comment]
Is CI work yet... ?
/retest-ubuntu

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by dgibson** [comment]
@fidencio well, the CI failures I did have are gone, but alas there's now a static check failure that's *definitely* not to do with this patch instead.

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.
