### PR TITLE
logging: Replace nix::Error::EINVAL with more descriptive msgs

### LINKED ISSUE #954: Return meaningful error message for Errs
In agent there are many `Error`s returned by:

```rust
return Err(anyhow!(nix::Error::from_errno(Errno::EINVAL)));
```

With this we might only get an error message of "Invalid argument".

These errors are lack of detail information about the error, hard to understand, and not user friendly.

`Error`s should contains more meaningful information.

### PR DESCRIPTION
**Pull request by bookinabox**
Replaces instances of anyhow!(nix::Error::EINVAL) with other messages to
make it easier to debug.

Fixes #954

Signed-off-by: Derek Lee <derlee@redhat.com>

### CODE REVIEW

**Comment by bookinabox** [comment]
I'm not too familiar with the internals of the agent or rust, so please let me know if there are any inaccuracies or bad practices.

File: src/agent/rustjail/src/mount.rs [hunk 1]
```diff
@@ -1041,7 +1044,10 @@ fn mask_path(path: &str) -> Result<()> {
 
 fn readonly_path(path: &str) -> Result<()> {
     if !path.starts_with('/') || path.contains("..") {
-        return Err(anyhow!(nix::Error::EINVAL));
+        return Err(anyhow!(
+            "Cannot mount {} (path does not start with '/' or contains ...",
```
Comment (ManaSugi) [inline src/agent/rustjail/src/mount.rs:1048]: It might be a good:

```
"Cannot mount {} (path does not start with '/' or contains '..')."
```

File: src/agent/rustjail/src/mount.rs [hunk 2]
```diff
@@ -1021,7 +1021,10 @@ pub fn finish_rootfs(cfd_log: RawFd, spec: &Spec, process: &Process) -> Result<(
 
 fn mask_path(path: &str) -> Result<()> {
     if !path.starts_with('/') || path.contains("..") {
-        return Err(anyhow!(nix::Error::EINVAL));
+        return Err(anyhow!(
+            "Cannot mount {} (path does not start with '/' or contains ...)",
```
Comment (ManaSugi) [inline src/agent/rustjail/src/mount.rs:1025]: It might be a good:

```
"Cannot mount {} (path does not start with '/' or contains '..')."
```

**Review by ManaSugi — COMMENTED** [review]
Thank you for improving the error messages! I have a few comments.

**Comment by bookinabox** [comment]
Thanks for the feedback!

**Comment by ManaSugi** [comment]
> @bookinabox Please check the format by running `cargo fmt -- --check`. https://github.com/kata-containers/kata-containers/runs/7667490131?check_suite_focus=true#step:12:81

@bookinabox  Could you check it as well?

**Comment by bookinabox** [comment]
> > @bookinabox Please check the format by running `cargo fmt -- --check`. https://github.com/kata-containers/kata-containers/runs/7667490131?check_suite_focus=true#step:12:81
> 
> @bookinabox Could you check it as well?
Hmm, I did run it. Let me double check all my versions are the same and the specific file its failing at. Sorry about that.

**Comment by ManaSugi** [comment]
@bookinabox Thank you for the update

> well, I changed my versions to the ones on the runner. Not sure if that's what fixed it, but fmt did change stuff now.

JFYI: Kata maintains the version information in the [versions.yaml](https://github.com/kata-containers/kata-containers/blob/main/versions.yaml) and the current Rust version Kata uses is bellow.
https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L306

**Comment by bookinabox** [comment]
> @bookinabox Thank you for the update
> 
> > well, I changed my versions to the ones on the runner. Not sure if that's what fixed it, but fmt did change stuff now.
> 
> JFYI: Kata maintains the version information in the [versions.yaml](https://github.com/kata-containers/kata-containers/blob/main/versions.yaml) and the current Rust version Kata uses is bellow. https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L306

Thanks!

**Comment by ManaSugi** [comment]
@bookinabox if the PR are ready, please remove the draft status.

**Review by ManaSugi — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bookinabox!

File: src/agent/rustjail/src/mount.rs [hunk 3]
```diff
@@ -1041,7 +1044,10 @@ fn mask_path(path: &str) -> Result<()> {
 
 fn readonly_path(path: &str) -> Result<()> {
     if !path.starts_with('/') || path.contains("..") {
-        return Err(anyhow!(nix::Error::EINVAL));
+        return Err(anyhow!(
```
Comment (jodh-intel) [inline src/agent/rustjail/src/mount.rs:1047]: It might be worth creating a common check function for this and `mask_path()` to avoid the duplicated code so both functions could start with something like:

```rust
check_path(path)?;

// ...
```

File: src/agent/rustjail/src/validator.rs [hunk 4]
```diff
@@ -4,17 +4,15 @@
...
 
-fn einval() -> Error {
-    anyhow!(nix::Error::EINVAL)
-}
-
 fn get_linux(oci: &Spec) -> Result<&Linux> {
-    oci.linux.as_ref().ok_or_else(einval)
+    oci.linux
+        .as_ref()
+        .ok_or_else(|| anyhow!("Unable to get Linux from Spec"))
```
Comment (jodh-intel) [inline src/agent/rustjail/src/validator.rs:15]: Nit: This makes sense to developers but might be clearer for end users as something like:

```suggestion
        .ok_or_else(|| anyhow!("Unable to get Linux section from Spec"))
```

But, either way, this message is inconsistent with the (redundant) same check on the Linux spec in `src/agent/rustjail/src/container.rs`.

File: src/agent/rustjail/src/container.rs [hunk 5]
```diff
@@ -1437,16 +1437,18 @@ impl LinuxContainer {
             Some(unistd::getuid()),
             Some(unistd::getgid()),
         )
-        .context(format!("cannot change onwer of container {} root", id))?;
+        .context(format!("Cannot change owner of container {} root", id))?;
 
         if config.spec.is_none() {
-            return Err(anyhow!(nix::Error::EINVAL));
+            return Err(anyhow!("Cannot create the container: the spec is none"));
```
Comment (jodh-intel) [inline src/agent/rustjail/src/container.rs:1443]: - Nit: You could make this shorter and not lose detail:

  ```suggestion
            return Err(anyhow!("Cannot create the container: no spec"));
  ```
- For strings with no format specifiers like this, I'd be tempted to define them as top-level `const` values. That also means the unit tests can reference those variables to assert the expected message when they provoke errors.

File: src/agent/rustjail/src/cgroups/fs/mod.rs [hunk 6]
```diff
@@ -174,7 +174,9 @@ impl CgroupManager for Manager {
                 freezer_controller.freeze()?;
             }
             _ => {
-                return Err(anyhow!(nix::Error::EINVAL));
+                return Err(anyhow!(
+                    "Invalid FreezerState. Must be FreezerState::Frozen or FreezerState::Thawed"
```
Comment (jodh-intel) [inline src/agent/rustjail/src/cgroups/fs/mod.rs:178]: I'd consider inverting this as although the message is superficially helpful, it doesn't result in the actual state being logged, so doesn't help developers. I'm being arguably overly harsh/pedantic here as there is only one other state, but what if there are >1 other states in future?

I'd just log something like:

```suggestion
                    "Invalid FreezerState: {:?}", state
```

Of course, that won't currently work as FreezerState` doesn't support `Display`/`Debug`, but I think it should. If you're keen, you might want to raise a PR on https://github.com/kata-containers/cgroups-rs to add atleast `#[derive(Debug)]` to the `enum`.

File: src/agent/rustjail/src/container.rs [hunk 7]
```diff
@@ -1437,16 +1437,18 @@ impl LinuxContainer {
...
         }
 
         let spec = config.spec.as_ref().unwrap();
 
         if spec.linux.is_none() {
-            return Err(anyhow!(nix::Error::EINVAL));
+            return Err(anyhow!(
+                "Cannot create the container: the linux spec is none"
```
Comment (jodh-intel) [inline src/agent/rustjail/src/container.rs:1450]: Interestingly, both this check and the one above are technically redundant because the first thing the function does is call `validate()` which already performs these checks.

File: src/agent/rustjail/src/validator.rs [hunk 8]
```diff
@@ -31,7 +29,10 @@ fn rootfs(root: &str) -> Result<()> {
     let path = PathBuf::from(root);
     // not absolute path or not exists
     if !path.exists() || !path.is_absolute() {
-        return Err(einval());
+        return Err(anyhow!(
+            "Path from {} does not exist or is not absolute",
```
Comment (jodh-intel) [inline src/agent/rustjail/src/validator.rs:33]: I'd use `{:?}` for all paths to ensure they are quoted (so you can see if they are blank).

File: src/agent/rustjail/src/validator.rs [hunk 9]
```diff
@@ -58,10 +59,10 @@ fn rootfs(root: &str) -> Result<()> {
         cleaned.push(e);
     }
 
-    let canon = path.canonicalize().context("canonicalize")?;
+    let canon = path.canonicalize().context("failed to canonicalize path")?;
     if cleaned != canon {
         // There is symbolic in path
-        return Err(einval());
+        return Err(anyhow!("Cleaned and canonicalized path do not match. There may be illegal symbols in the path name"));
```
Comment (jodh-intel) [inline src/agent/rustjail/src/validator.rs:65]: - The invalid path isn't being logged in the message so this is reliant on the caller logging it. Could you check/adjust as necessary?
- This canonicalisation check is another one that could be added to a new `check_path()` function possibly.

**Review by jodh-intel — COMMENTED** [review]
Thanks @bookinabox - a few comments...

File: src/agent/rustjail/src/mount.rs (hunk 3 above)
Comment (jodh-intel) [reply src/agent/rustjail/src/mount.rs:1047]: ... if you did do this (possibly on anther PR), you could consider writing a set of table-based tests:

- https://github.com/kata-containers/kata-containers/blob/main/docs/Unit-Test-Advice.md#rust-table-driven-tests

There are lots of examples of these in the repo - search for `TestData` to find a bunch.

**Comment by ManaSugi** [comment]
@bookinabox 
Could you also replace remaining `EINVAL` with detailed messages?

```
src/rpc.rs
180:                return Err(anyhow!(nix::Error::EINVAL));
250:            return Err(anyhow!(nix::Error::EINVAL));
1930:        return Err(anyhow!(nix::Error::EINVAL));

src/netlink.rs
615:        let v = u8::from_str_radix(split.next().ok_or_else(|| anyhow!(nix::Error::EINVAL))?, 16)?;
```

File: src/agent/rustjail/src/container.rs (hunk 5 above)
Comment (bookinabox) [reply src/agent/rustjail/src/container.rs:1443]: If we want to take it a step further I could try to convert the errors to use thiserror instead of anyhow, though that might be a little overkill. I do see thiserror being used a couple other places.

File: src/agent/rustjail/src/validator.rs (hunk 9 above)
Comment (bookinabox) [reply src/agent/rustjail/src/validator.rs:65]: I was working on a different [issue](https://github.com/kata-containers/kata-containers/issues/1378) converting String to OsString/Paths. While I haven't look at this too closely, it looks like this is making sure that paths are valid Strings. Perhaps we might not need this check in the future if we are able to properly replace String instances?

**Comment by bookinabox** [comment]
^ didn't run clippy, so I had an error not caught by fmt

**Comment by bookinabox** [comment]
Should have learned my lesson. It should pass now. I remembered to run test, clippy, and fmt.
