### PR TITLE
runtime: don't fail mkdir if the folder is already created by another process

### LINKED ISSUE #5713: container creation fails when trying to mkdir /run/vc/vm
# Description of problem

When trying to create multiple containers at the same time some of them might fail because multiple processes try to create the folder /run/vc/vm.

### PR DESCRIPTION
**Pull request by alex-matei**
In case a folder is created by another process continue without generating an error.

Fixes #5713

Signed-off-by: Alexandru Matei <alexandru.matei@uipath.com>

### CODE REVIEW

File: src/runtime/virtcontainers/utils/utils.go [hunk 1]
```diff
@@ -397,26 +397,38 @@ func MkdirAllWithInheritedOwner(path string, perm os.FileMode) error {
...
+
+		err = os.Mkdir(curPath, perm)
+		if err == nil {
 			if err = syscall.Chown(curPath, uid, gid); err != nil {
 				return fmt.Errorf("chown syscall failed: %v", err.Error())
 			}
 			continue
 		}
 
+		if !os.IsExist(err) {
```
Comment (amshinde) [inline src/runtime/virtcontainers/utils/utils.go:421]: You dont need to check for if the directory exists here again. Just check for in the else clause of the previous if statement.

Comment (alex-matei) [reply src/runtime/virtcontainers/utils/utils.go]: Thanks @amshinde, updated.

File: src/runtime/virtcontainers/utils/utils.go [hunk 2]
```diff
@@ -399,12 +399,14 @@ func MkdirAllWithInheritedOwner(path string, perm os.FileMode) error {
 		info, err := os.Stat(curPath)
 
 		if err != nil {
-			if err = os.Mkdir(curPath, perm); err != nil {
+			err = os.Mkdir(curPath, perm)
```
Comment (bergwolf) [inline src/runtime/virtcontainers/utils/utils.go:402]: What about just calling `os.MkdirAll` and do not care about EEXIST errors?

Comment (alex-matei) [reply src/runtime/virtcontainers/utils/utils.go]: Good idea, changed the code to use MkdirAll.

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @alex-matei !

**Review by fidencio — APPROVED** [review]
lgtm, thanks @alex-matei!

**Review by bergwolf — APPROVED** [review]
lgtm!
